### ISSUE TITLE
Too small font size for CJK (Chinese, Japanese and Korean) interface

### ISSUE THREAD

**Issue by zerng07** [elementary/stylesheet#10]
CJK characters have many vertical and horizontal strokes in one character. It might be as simple as only one veritcal or horizontal stroke like 一丨, or as complex as something like 轟麤龘.

Small font size are almost unable to read easily with the default settings. CJK people usually expect font size 12 as the general good-reading and comfortable one. 

The font size 11 is bearable as the lower boundary of legibility for fluent reading. 
The font size less than or equal to 10 is not recommended, and can only be accepted in few situations if there is still a need to have small size font displayed.

Sorry that I don't know much about programming, but I found you specify the size of the text body as 12 already. [1] The font size still looks small than other desktop environments, such as GNOME shell (on my Fedora platform) which uses size 11 as the default one. There might be some problems in there. 

Please take this problem into consideration! This will help you do a better internationalization job and be more friendly in East Asia. :)

1. http://old.elementary.io/journal/typography-gtk3

**Comment by danrabbit** [comment]
This isn't something that can be done in the stylesheet. You might want to file an issue against [elementary OS in Launchpad](https://bugs.launchpad.net/elementaryos)
