### ISSUE TITLE
[odin beta] ActionBar incorrectly receives color_primary background color

### ISSUE THREAD

**Issue by ztefn** [elementary/stylesheet#1004]
I think **color_primary** is only intended as background color for the TitleBar/HeaderBar (as in previous releases).

Screenshot showing an action bar in the bottom of a sidebar:
![Screenshot from 2021-05-01 16-11-34](https://user-images.githubusercontent.com/343442/116788510-7edc0a00-aa99-11eb-9ff5-f08d0c50882b.png)

**Comment by ztefn** [comment]
This issue is still present in the final release of elementary OS 6

**Comment by danrabbit** [comment]
Hey thanks for your issue report. This is an intention feature that was requested by some other app developers. You can use `Gtk.STYLE_CLASS_FLAT` if you'd like a neutral inline toolbar style instead

Closing as "Design conflict" since this is a feature that was implemented by request
