### ISSUE TITLE
[odin beta] Linked buttons in HeaderBar do not follow color_primary

### ISSUE THREAD

**Issue by ztefn** [elementary/stylesheet#1005]
Thus sticking out instead of blending in, see _Add_ and _Refresh_ buttons in the example below:

![Screenshot from 2021-05-01 16-11-34](https://user-images.githubusercontent.com/343442/116788623-25c0a600-aa9a-11eb-852e-bc4fd6a5bf4b.png)

**Comment by ztefn** [comment]
This issue is still present in the final release of elementary OS 6

**Comment by cassidyjames** [comment]
Raised and linked buttons intentionally sport a raised look for improved contrast across styles. When designing the new stylesheet we had to balance the wants and needs of our first-party apps, hundreds of AppCenter apps, and some level of GNOME compatibility.

It's possible we could update the raised style in header bars to base off the primary color, but then it won't be possible to keep it in sync with the elevation levels used elsewhere throughout the stylesheet, so we trade one request with reduced consistency and increased maintenance costs.

One option you could experiment with would be to either mark your other headerbar buttons as raised to match the styling (more like how your app looks on GNOME), or to consider not linking those two buttons if you don't like how they appear. Alternately of course you're welcome to include custom styles so your app looks exactly how you want on elementary OS.

**Comment by ztefn** [comment]
I decided to drop the use of primary color altogether, too much broken and unpolished things.
