### ISSUE TITLE
Google Chrome close/maximize buttons are too close to the edge of the window

### ISSUE THREAD

**Issue by arkaitzsilva** [elementary/stylesheet#1007]
## What Happened
Google Chrome close/maximize buttons on both sides of the header bar are too close to the edge of the window.

Elementary OS 5 and 6 comparison:

Elementary OS 5:
![google-chrome-e-5](https://user-images.githubusercontent.com/37912316/116792872-aea00780-aac3-11eb-84c5-292143ecd356.png)

Elementary OS 6:
![google-chrome-e-6](https://user-images.githubusercontent.com/37912316/116792880-b8c20600-aac3-11eb-9b70-1a4f00a1e8f7.png)

## Expected Behavior
Minimum separation from the edge of the window like in Elementary OS 5.

## Steps to Reproduce
I installed the google-chrome-stable deb package from google repository to reproduce the issue.

## Platform Information
Tested on elementary OS 6

**Comment by danrabbit** [comment]
Chrome uses a custom toolkit instead of native Gtk widgets. Please report this issue to Google

**Comment by BAProductions** [comment]
Tell Chrome to gtk theme in chrome setting

### **Before**
![Screenshot from 2021-09-09 22-41-13](https://user-images.githubusercontent.com/2386630/132790666-e9638839-9626-4b46-9d1d-63254bb7a0be.png)

### **After**
![Screenshot from 2021-09-09 22-39-37](https://user-images.githubusercontent.com/2386630/132790673-9bb0da32-f0d0-412e-b165-bb10bc90c55e.png)
