### ISSUE TITLE
non elementary apps like nautilus , firefox dont follow system theme .

### ISSUE THREAD

**Issue by meliodas1107** [elementary/stylesheet#1008]
## What Happened

No dark mode is there for non elementary apps . Instead of making them look in light mode , better make them use at least adwaita dark(or make them use elementary theme like it uses in light mode ?)

## Expected Behavior

All apps to follow system theme .

## Steps to Reproduce

1.open settings 
2.Go to desktop 
3.Go to appearance and change to dark mode 
4.Install an app like firefox or nautilus  and it will be using light theme.
![Screenshot from 2021-05-02 04 31 28](https://user-images.githubusercontent.com/57810820/116802381-b7173300-ab01-11eb-9e09-6df91e76fc53.png)

## Platform Information

![image](https://user-images.githubusercontent.com/57810820/116802406-e4fc7780-ab01-11eb-889d-973a30d0ceaa.png)

**Comment by cassidyjames** [comment]
We're working with GNOME on a FreeDesktop initiative for a system-wide dark style, but it has not been accepted/implemented by GNOME yet. elementary and GNOME designers agree it is critical that such an effort is opt-in for apps, so apps will use the light style unless they update to follow the preference.

We will not manually force apps to use a different stylesheet than what the app requests, so there's nothing to do for us here.
