### ISSUE TITLE
Gtk.Notebook has no borders

### ISSUE THREAD

**Issue by ryonakano** [elementary/stylesheet#1010]
## What Happened

![Screenshot from 2021-05-02 16-30-32](https://user-images.githubusercontent.com/26003928/116805843-0d1cc280-ab64-11eb-9038-cd33e03ca2a9.png)

Gtk.Notebook in Web has no borders and is not visually unified with Granite.Widgets.DynamicNotebook.

## Expected Behavior

Gtk.Notebook in Web should have borders and be visually unified with Granite.Widgets.DynamicNotebook, like this:

![Screenshot from 2021-05-02 16-32-03](https://user-images.githubusercontent.com/26003928/116805900-85838380-ab64-11eb-9bc7-d9dbee6210d6.png)

## Steps to Reproduce

1. Open Web
2. See the tab bar

### Logs

N/A

## Platform Information

- elementary OS 6 Early Access with fully updated
- *Flatpaked* GNOME Web 40.0

**Comment by hanaral** [comment]
Isn't that libadwaita rather than gtk or did it get downstreamed?

**Comment by cassidyjames** [comment]
Yeah I'm like 90% sure this isn't GtkNotebook but was the new Hdy tab switcher which is now styled. Feel free to re-open if I'm wrong.
