### ISSUE TITLE
[odin-beta] Non-default applications do not respect dark mode set in System Settings

### ISSUE THREAD

**Issue by GlasierXplor** [elementary/stylesheet#1014]
## What Happened

The default Pantheon applications (except for GNOME Web, [Issue #11 on Browser](https://github.com/elementary/browser/issues/11)) follows the dark mode as turned on in the System Settings (expected behaviour). Any additional applications installed will not respect this setting.

I have so far installed a few applications to test out, including the included Dconf Editor, Firefox, Libreoffice, OnlyOffice Desktop Editors, and GNOME System Monitor. All applications opened as light mode instead of dark mode.

E.g. Firefox's, OnlyOffice's, and LireOffice's "Save as" file dialogue boxes spawned in light mode, all applications have light title bars (not much of a problem, just that it does not fit the aesthetics of the rest of the system).

## Expected Behavior

Externally installed applications should respect the dark mode as set in the System Settings.

## Steps to Reproduce

1. Turn on dark mode in the System Settings > Desktop > Appearance > Style: Dark
2. Install applications using `apt-get` in Terminal. E.g. `sudo apt-get install firefox`
3. Open installed application and notice that they have been spawned as light mode (light grey title bars, file saving dialogue boxes spawn in light mode)

### Logs

No logs present (Checked `/var/log/syslog`, `/var/log/Xorg.0.log`)

## Platform Information

Elementary OS public beta downloaded from builds.elementary.io (`elementary-os-6.0-daily-20210430.iso`)

**Comment by GlasierXplor** [comment]
Even though I found a file `/home/user/.config/gtk-3.0/settings.ini`, but the System Settings changes does not seem to affect this file. There were some errors that I have noticed if this file is present in `/var/log/syslog`. The errors were consistent with all non-native applications.

**GNOME System Monitor**
```
May  9 17:29:40 virtual-machine-8535d256 io.elementary.w[1496]: RelevancyService.vala:166: Pushing launch event: application://gnome-system-monitor.desktop [System Monitor]
May  9 17:29:40 virtual-machine-8535d256 gnome-system-mo[12930]: Failed to parse /home/timothy/.config/gtk-3.0/settings.ini: Key file does not start with a group
May  9 17:29:40 virtual-machine-8535d256 gala[1451]: clutter_actor_remove_child: assertion 'CLUTTER_IS_ACTOR (child)' failed
May  9 17:29:40 virtual-machine-8535d256 gala[1451]: invalid (NULL) pointer instance
May  9 17:29:40 virtual-machine-8535d256 gala[1451]: g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed
```

I have added a `[Settings]` line to the file in accordance to "known good" `settings.ini` I have seen on other forums. The errors have disappeared, and the non-native applications now respect the dark mode.

`/home/user/.config/gtk-3.0/settings.ini`
**Original**
```
gtk-application-prefer-dark-theme=0
```

**Updated**
```
[Settings]
gtk-application-prefer-dark-theme=0
```

**Comment by danrabbit** [comment]
This is to be expected. The dark style preference is opt-in as detailed in our blog post [here](https://blog.elementary.io/the-need-for-a-freedesktop-dark-style-preference/)
