### ISSUE TITLE
Folders' color same as accent, if possible. EOS 6 Beta

### ISSUE THREAD

**Issue by KarkanAlzwayed** [elementary/stylesheet#1034]
This is not an issue. More of a feature request in the style sheet/look and feel.

I was browsing around the gnome-look .org and ran into this [icon theme](https://www.gnome-look.org/p/1427890/) It has the elementary OS icons in all the accent colors that EOS ships with, like one by one (except that it has an extra "black" and "silver" folders). Thought it would be very nice to have the folders change to the same color as the accent when changed in settings>desktop>appearance>accent. So, instead of resorting to third party theming, this could be a nice addition to, an already, beautiful style of EOS.

**Comment by jeremypw** [comment]
This feels like a misuse of accent color - which, as I understand it - is intended to draw attention to some particular item state (e.g. selected).

**Comment by KarkanAlzwayed** [comment]
> This feels like a misuse of accent color which, as I understand it, is intended to draw attention to some particular item state (e.g. selected).

I don't understand how it's a misuse to be honest. If anything, it'd make the distro more unified in terms of style and look better. For each their own, though.

**Comment by cassidyjames** [comment]
We've explicitly decided to keep the manila icon color instead of using an accent color for icons.

**Comment by KarkanAlzwayed** [comment]
> We've explicitly decided to keep the manila icon color instead of using an accent color for icons.

Fair enough. Hence the "if possible". Thanks
