### ISSUE TITLE
Add support for GTK4

### ISSUE THREAD

**Issue by Macintosh98** [elementary/stylesheet#1039]
## Problem

Add support for GTK4

## Proposal

The current stylesheet only supports GTK3, it would be great to support GTK4 so that application creators can switch to the new toolkit without fearing theming incompatibilities

## Prior Art

No real prior art than Adwaita and the internal GTK theme

**Comment by Letterus** [comment]
I raised my sponsorship to make a strong vote for this issue and the migration to Gtk4, to not get left behind the development train traveling further to Gtk4 and Wayland. @cassidyjames @danrabbit

**Comment by danrabbit** [comment]
@Letterus thank you very much for your sponsorship!

GTK4 is a high priority for us. We're now building OS 7 images in early access that should have the development libraries we need to start working on GTK 4. We're also testing a 6.1 Flatpak runtime that contains GTK4. We're doing our best to put a bow on OS 6 and shift development focus to OS 7 in the new year. I'll be sure to bring this up again to the team this morning in our standup meeting to make sure we nail down a more definitive timeline and set priorities, but I'm expecting that I can start working on imminently.

My highest priority this week is release management for this month's updates, but what I can do here is use Thursday's live stream to look at GTK4 porting :)

**Comment by Letterus** [comment]
Thank you for coming back to Gtk4 so quickly, like doing the stylesheet draft, example port, Gtk4 GitHub project and YT stream. That was not expected so closely (especially as you seem to be sick right now), but it's highly appreciated and thank you very much!

**Comment by danrabbit** [comment]
Since this is going to be a much bigger project than just a single issue report, I've opened https://github.com/elementary/stylesheet/projects/5 and I'm going to close this issue report in favor of that. There's rudimentary support for GTK4 now here, so we just have to track issues related to cleaning it up and fixing issues
