### ISSUE TITLE
gala-multitaskingview.desktop Icon reference in different language wrong

### ISSUE THREAD

**Issue by m4st3r-bl4ckb1rd** [elementary/stylesheet#1044]
## What Happened
multitask view icon not showd in german

## Expected Behavior
multitask view icon not showd in german

## solution
no not translate Icon[xx]= part in gala-multitaskingview.desktop
`Icon[de]=Übersicht der Arbeitsfläschen
Icon[mr]=मल्टीटास्किंग-व्ह्यू
`

**Comment by tintou** [comment]
Thanks this is now fixed in master.
