### ISSUE TITLE
White title bar inspite choosing the dark theme

### ISSUE THREAD

**Issue by saurabhlambe** [elementary/stylesheet#1057]
## What happened
This is the Odin beta 2 release. I installed the _kitty_ terminal the other day. I have the dark theme set. I could still see the _kitty_ title bar in white.

## Expected Behavior
The kitty title bar should match the system theme or is there a way to make the title bar transparent so that I only have the terminal and nothing else on the screen?

## Steps to Reproduce
1. Set the global theme to "dark"
2. Install _kitty_ terminal
`sudo apt install -y kitty`
3. Launch kitty

## Platform Information
**OS information:**
`NAME="elementary OS"
VERSION="6 Early Access"
ID=elementary
ID_LIKE=ubuntu
PRETTY_NAME="elementary OS 6 Early Access"
LOGO=distributor-logo
VERSION_ID="6"
HOME_URL="https://elementary.io/"
DOCUMENTATION_URL="https://elementary.io/docs/learning-the-basics"
SUPPORT_URL="https://elementary.io/support"
BUG_REPORT_URL="https://github.com/elementary/os/issues/new"
PRIVACY_POLICY_URL="https://elementary.io/privacy-policy"
VERSION_CODENAME=odin
UBUNTU_CODENAME=focal`

**Kitty version:**
`kitty 0.15.0 created by Kovid Goyal`

## Screenshot
![image](https://user-images.githubusercontent.com/19834688/122631996-6e392f00-d0ed-11eb-97ad-500a26ce82f2.png)

**Comment by cassidyjames** [comment]
Apps must opt into using a dark style in response to the user preference; we never forcefully override a style for apps. You can read more here: https://blog.elementary.io/the-need-for-a-freedesktop-dark-style-preference/

**Comment by saurabhlambe** [comment]
@cassidyjames thank you for the quick update. I observed the same behaviour with Atom editor. Does the same apply to this app too?

**Comment by cassidyjames** [comment]
@saurabhlambe yes, exactly. We're pursuing a cross-desktop effort so it's easier for apps targeting elementary OS, Ubuntu, GNOME, KDE, "Linux," etc. to al follow a similar preference while keeping apps from breaking in unexpected ways. We're the first to ship it, but we're working with GNOME folks closely as well and I believe we will align on something under the FreeDesktop umbrella soon.
