### ISSUE TITLE
Java app windows do not completely follow the UI design (Ex: intellj idea)

### ISSUE THREAD

**Issue by send2r** [elementary/stylesheet#1063]
## What Happened
Running java applications such as eclipse or Intellij idea stands out from the basic UI design

## Expected Behavior
Unified experience across apps

## Steps to Reproduce
Download and run a Java based app such as intellij Idea
Attached screenshot - the bottom corner radius is not present for Java based app window (compare against terminal in the background)
Similar appearance is noted for apps like Opera browser

### Logs
NA
## Platform Information
Elementary os 6 early access
![Screenshot from 2021-07-31 11 30 50@2x](https://user-images.githubusercontent.com/13864239/127730458-42ff4a8b-d4d6-487b-a863-96ca30b79477.png)

**Comment by danrabbit** [comment]
There's not really anything we can do about this. Closing as "Out of scope" since this is an app/toolkit problem
