### ISSUE TITLE
Active tab on Epiphany is taller than the tab bar

### ISSUE THREAD

**Issue by dar5hak** [elementary/stylesheet#1064]
## What Happened

I have a LoDPI display with 1366×768 resolution. The active tab on Epiphany looks like this:

![Screenshot from 2021-07-31 16 48 29](https://user-images.githubusercontent.com/8205055/127738551-601d8c17-5cb1-46d2-9c38-5b30af829682.png)

It looks fine on other apps like Terminal and Code. Inactive tabs also look all right.

## Expected Behavior

The tab should fit within the tab bar.

## Steps to Reproduce

1. Open Epiphany on a 1366×768 display (assuming this is a resolution problem).
2. Or let me know how to debug.

### Logs

Visual bug.

## Platform Information

Odin beta, but I have seen this on older dailies too. Epiphany is the preinstalled Flatpak version, updated to the latest.

**Comment by cassidyjames** [comment]
@dar5hak beta1 or beta2? It looks like you might have an outdated Flatpak configuration, because this was fixes a while ago and I can't reproduce it here. You might try:

```
sudo flatpak install --system -y appcenter \
    io.elementary.calculator//stable \
    io.elementary.camera//stable \
    io.elementary.screenshot//stable \
    io.elementary.tasks//stable \
    org.gnome.Epiphany//stable \
    org.gnome.Evince//stable
```

**Comment by dar5hak** [comment]
@cassidyjames Thanks! That fixed it. Turns out I had both daily and stable Flatpaks installed, and my dock icon was probably pointing to the wrong one. All good now. :+1:
