### ISSUE TITLE
IBus-pinyin popover shows cursor as black rectangle, obscuring the text

### ISSUE THREAD

**Issue by jeremypw** [elementary/stylesheet#1067]
## What Happened

 - Installed the "Intelligent Pinyin" input method.
 - Selected "Chinese (Intelligent Pinyin) using Wingpanel
 - Opened Code and typed (e.g.) "xi" into new document
 - The pinyin popover opens - the first option is obscured.

![IntelligentPinyin](https://user-images.githubusercontent.com/10513844/127903455-97947ee8-a19c-4e7b-af56-ec9846be97bf.png)

Note that carrying out the same steps on Ubuntu Focal with the default theme gives the following:

![Screenshot from 2021-08-02 18 36 38](https://user-images.githubusercontent.com/10513844/127903593-9a95a95a-33c4-49cd-bdba-416bb2f6e2ef.png)

This indicates the issue is (probably) caused by the elementary theming.

## Expected Behavior

The cursor is displayed without obscuring the text.

## Platform Information

Odin daily.

**Comment by ryonakano** [comment]
I suppose this is where IBus appends candidate texts:

https://github.com/phuang/ibus/blob/99e4d9d7af0bdeaf396bbd26cac949eca7cdfe1d/ui/gtk3/candidatearea.vala#L87-L125

Maybe the style context `Gtk.StateFlags.SELECTED` related to the issue?

**Comment by ryonakano** [comment]
FYI I face this issue when I typing Japanese in Inkscape, so it's not issue in libpinyin―maybe because of a style class used in the IBus Candidate window.

![2021-08-22 14 09 34 のスクリーンショット](https://user-images.githubusercontent.com/26003928/130343166-c76d7655-adce-4def-bb15-76221d141285.png)

**Comment by jeremypw** [comment]
The issue occurs for Japanese-Mozc in Inkscape but not in e.g. Code or Firefox whereas it always occurs with Chinese Intelligent Pinyin so I am not sure what is going on.  Any stylesheet should give contrasting colours for foreground and background colors in any state.  It is noticeable that in Ubuntu the selection rectangle covers both the digit and the character and the digit and character have different colors so there are at least three styles involved.  In elementary, all the text is black and the character has a black background.  Presumably the selection rectangle is transparent (:shrug:).  Perhaps there are missing styles which are just rendered as black.

**Comment by jeremypw** [comment]
This is what I get typing Japanese into Code.  Note that the selection rectangle again covers both digit and suggestion.
![JapaneseCodeSelection (1)](https://user-images.githubusercontent.com/10513844/130350751-9856cb43-f133-4b57-87ba-fc670a02098c.png)

**Comment by ryonakano** [comment]
OK, now I created a PR to fix this thanks to https://github.com/ibus/ibus/issues/1871:

![](https://user-images.githubusercontent.com/26003928/141889308-e996aac4-2c41-44d4-b517-9f8c4f10fc43.png)
