### ISSUE TITLE
ModelMenu "basement" navigation too tall

### ISSUE THREAD

**Issue by kdwk** [elementary/stylesheet#1070]
## What Happened

![Screenshot from 2021-08-08 21-18-23](https://user-images.githubusercontent.com/39268094/128633390-5853ebac-ad5b-4099-bdd4-bd00377bfc3a.png)

The highlighted bar is a little too thick. 

## Expected Behavior

We should probably make it thinner.

## Steps to Reproduce

1. Open Web
2. Click on 'cog' icon
3. Click on 'Import and export'
4. Hover on the 'go back' button

## Platform Information

Flatpak org.gnome.Epiphany 3.38.3

**Comment by danrabbit** [comment]
It looks like this is fixed in GTK4. These title/navigation items get the same height as other menu items
