### ISSUE TITLE
Highlight color not rendered in Thunderbird and Eclipse

### ISSUE THREAD

**Issue by stan-janssen** [elementary/stylesheet#1073]
## What Happened

![highlight-foreground](https://user-images.githubusercontent.com/12174852/129087457-0e0d9aab-a020-4f8e-ac93-0569e6458b8e.png)

In elementaryOS 6.0, in certain applications, highlighted text displays as a very dark grey with a white background, instead of showing a blue highlight color. I encountered this problem in Thunderbird 78 (latest version) and Eclipse.

- I'm not sure this is the correct place to report this problem.
- This problem was not present in elementaryOS 5.1.7 which I was using previously.
- This problem is independent of which highlight color is selected in System Settings
- When the window is not in focus, the highlight is properly rendered:

![highlight-background](https://user-images.githubusercontent.com/12174852/129087568-b88a37b8-26ab-4f65-96ae-c1875851d3ff.png)

- The same behaviour occurs in Eclipse IDE 2020-06:

![highlights-eclipse](https://user-images.githubusercontent.com/12174852/129088432-c6c2681f-2ae9-428b-9972-e7f91b7f9ec1.png)

- These applications are all freshly installed on a fresh install of elementaryOS 6 on real hardware (the same hardware that ran elementaryOS 5 previously).

## Expected Behavior
I expect the highlighted text to be the same in Thunderbird and Eclipse as it is in all other applications.

## Steps to Reproduce

It happens in both the message viewer and the compose window:

- Install thunderbird from apt, open a message, select some text.
- Install thunderbird from apt, create a new message, type some text and select it.

## Platform Information

elementaryOS 6.0 stable

**Comment by cassidyjames** [comment]
Thunderbird and Eclipse are both non-GTK apps; we don't have any control over their styling or codebases. We recommend installing third-party apps like these from [Flathub](https://flathub.org/) so the developers have more control over how they look and work.
