### ISSUE TITLE
Odin 6.0 FlatPak Apps Do Not Follow Dark Mode

### ISSUE THREAD

**Issue by ganakee** [elementary/stylesheet#1075]
## What Happened
During install of FlatPak applications, the application does not follow the dark mode theme enabled in Odin 6.0. Instead, FlatPak uses a default theme (light).

## Steps to Reproduce

Select Dark Mode in Odin 6.0.
Install a FlatPak application. 
Open FlatPak application and window dressing default (light) theme.

## Platform Information
OS Odin 6.0 (final 2021-08-10)

**Comment by danrabbit** [comment]
Apps must opt-in to the dark style in order to avoid breaking custom styles. If an app you use doesn't listen to the dark style preference, please file an issue with that app

Closing as "out of scope" because apps must opt-in

**Comment by BAProductions** [comment]
it should even if where to custom style brake I wouldn't mind at all

**Comment by BAProductions** [comment]
> ## What Happened
> During install of FlatPak applications, the application does not follow the dark mode theme enabled in Odin 6.0. Instead, FlatPak uses a default theme (light).
> 
> ## Steps to Reproduce
> Select Dark Mode in Odin 6.0. Install a FlatPak application. Open FlatPak application and window dressing default (light) theme.
> 
> ## Platform Information
> OS Odin 6.0 (final 2021-08-10)

IM working to turn it on
