### ISSUE TITLE
LibHandy windows top corners not rounded when maximized

### ISSUE THREAD

**Issue by kdwk** [elementary/stylesheet#1077]
## What Happened

![Screenshot from 2021-08-18 14-12-20](https://user-images.githubusercontent.com/39268094/129846925-2faaac35-18a1-4f4c-a65f-3da609cb1ff1.png)
_LibHandy window top corners_

![Screenshot from 2021-08-18 14-13-06](https://user-images.githubusercontent.com/39268094/129846988-0de6d37a-aa5c-498f-a113-f2b7534fe065.png)
_Normal Gtk window_

## Expected Behavior

Top corners of both LibHandy and Gtk windows are rounded

## Steps to Reproduce

1. Open a LibHandy window
2. Maximize it
3. Repeat with Gtk window

## Platform Information

elementary OS 6 Odin

**Comment by danrabbit** [comment]
I'm gonna close this as "Out of scope" since it's a LibHandy issue and it's no longer a problem in GTK4
