### ISSUE TITLE
Firefox csd titlebar corners not completely rounded when the window is not maximized

### ISSUE THREAD

**Issue by arkaitzsilva** [elementary/stylesheet#1079]
## What Happened
Firefox csd titlebar corners are not completely rounded when the window is not maximized.

![csd_rounded_headerbar_corneers](https://user-images.githubusercontent.com/37912316/130123127-a6a4b599-143c-4767-aae0-421950aec7b5.png)

## Expected Behavior
Completely rounded corners

## Steps to Reproduce

1. Install Firefox through Ubuntu repository (not the flatpak version)
2. Open Firefox app

## Platform Information
Elementary OS 6

**Comment by cassidyjames** [comment]
We don't control Firefox's client-side drawing and cannot fix this from our side. You'll need to open an issue on Firefox, as GTK applications are styled correctly.
