### ISSUE TITLE
The margin between checkbox & label for "Sort Folders before Files" should be larger

### ISSUE THREAD

**Issue by 4jNsY6fCVqZv** [elementary/stylesheet#1119]
### What Happened?

![Screenshot](https://user-images.githubusercontent.com/46536067/144086132-b9e40446-bd54-48cd-8d02-05ec4fc6bb15.png)

### Steps to Reproduce

Open the context menu of an existing file or folder in the file chooser dialog.

### Expected Behavior

see issue title.

### OS Version

6.x (Odin)

### Software Version

Latest release (I have run all updates)

**Comment by danrabbit** [comment]
Transferred to Stylesheet since this looks like a model menu

**Comment by jeremypw** [comment]
That menu is not a Files one - it is a Gtk one.  We do not swap out the TreeView in the filechooser (yet)
