### ISSUE TITLE
Icons in menus in GParted are cut off

### ISSUE THREAD

**Issue by andrewdbate** [elementary/stylesheet#1170]
### What Happened?

With GParted, the icons in the menus are cut off on the left, as shown in the following 16 second video:

https://user-images.githubusercontent.com/2998569/149635973-1ada00bd-683e-4fcb-b795-5a58074c17d3.mp4

This issue happens both in the elementary OS installer (where GParted is used for custom partitioning during install) and also if the user chooses to install GParted after install with `sudo apt install gparted`.

Whilst this may require application specific tweaks, I think that because GParted is so useful and because it is included in the installer, then it should be supported by the elementary OS theme.

### Steps to Reproduce

1. Open GParted
2. Click on the menus (e.g. the GParted or the Help menu) from the menubar.
3. The icons are cut off on the left-hand side due to their placement probably due to the stylesheet.

### Expected Behavior

The icons should not be cut off because they should be placed correctly (as they are on Gnome on Ubuntu, for example).

### OS Version

6.x (Odin)

### Software Version

Latest release (I have run all updates)

### Hardware Info

The same things happens on multiple computers, so I do not think this is specific to the display or graphics hardware.

**Comment by ernstki** [comment]
@danirabbit Would it be feasible to backport this to Horus?

I still see what's shown in the video, and it affects other Gtk (3) apps to the point where I've had to adapt by modifying `.desktop` files to add `/usr/bin/env GTK_THEME=Adwaita`.

That _works_, but if we're just a few lines of CSS away from a better fix that lets me keep using the elementary stylesheets, I'd be happy to attempt a PR for that.
