### ISSUE TITLE
How about extending accent colours to more parts of eOS?

### ISSUE THREAD

**Issue by Vitamin-Michi** [elementary/stylesheet#1187]
### Problem

^^^

### Proposal

^^^

**Comment by tintou** [comment]
Please use the template, we don't know what your problem is with this kind of answers.

**Comment by danrabbit** [comment]
Since there is no clear actionable direction here and OP hasn't updated using the template, I'm going to close this issue.

OP if you'd like to open a more free-form brainstorm, you can use the "Discussions" tab. Issues should be concise and actionable. Thanks!
