### ISSUE TITLE
entry.tagged

### ISSUE THREAD

**Issue by danirabbit** [elementary/stylesheet#1197]
### Problem

![Screenshot from 2022-04-15 09 54 55](https://user-images.githubusercontent.com/7277719/163598654-443bc150-397c-45d0-bd21-06e1b8cac484.png)

### Proposal

- [ ] fix padding
- [ ] make sure text is legilbe
- [ ] style close buttons

**Comment by Exalm** [comment]
That's a demo, it's not a widget apps actually use. And if apps copy it, they usually have completely different styles and hierarchy. For example:

![Screenshot from 2023-02-28 17-02-08](https://user-images.githubusercontent.com/1510457/221861571-544f337e-a49d-4b90-b27b-643909d46cfc.png)

So I don't think there's a lot of point in making gtk4-demo look nice here.

**Comment by danirabbit** [comment]
Ah okay that's good to know!
