### ISSUE TITLE
Round and shadow framed rich-list

### ISSUE THREAD

**Issue by danirabbit** [elementary/stylesheet#1207]
### Problem

![Screenshot from 2022-05-26 14 15 44](https://user-images.githubusercontent.com/7277719/170581501-5add5e5f-4022-4dd6-81cd-93a1584fff81.png)

### Proposal

![Screenshot from 2022-05-26 14 15 51](https://user-images.githubusercontent.com/7277719/170581525-85d64658-30f2-4c26-85b0-bc3e0c8d8902.png)

```
.rich-list.frame {
border-radius: 6px;
box-shadow: 0 1px 3px alpha(#000, 0.1);
margin-bottom: 3px;
}

.rich-list.frame row {
padding: 6px 12px;
}
```

**Comment by Exalm** [comment]
FWIW the lists in inspector and gtk4-demo use GtkFrame rather than .frame.

In libadwaita we ended up renaming libhandy's .content to .boxed-list and just use that and leaving .rich-list to die. I also hope to eradicate it from GTK5. :)

**Comment by danrabbit** [comment]
Yeah this is the only place we ever use this pattern tbh. I suppose it would be better to match what Gtk or Adw are doing. I don't have strong feelings here

**Comment by Exalm** [comment]
Well, one thing I want to do is to get .boxed-list into GTK itself, so we can have nice looking lists in inspector. In that case IMO it would make sense for you to match that, but of course right now it's a libadwaita-only thing...

Another place I'd like to use that in is libgcr -the gtk4 port uses a lot of boxed lists, and those are again GtkFrame + .rich-list inside it, so the style is broken and not fixable.

Might be worth it to poke gtk people.

**Comment by danrabbit** [comment]
Based on the conversation we had in Matrix I'm gonna continue in this direction using a frame class instead of a Gtk.Frame. And then at whatever point class names are decided in Gtk I'll migrate the styles to us the upstream names. Thanks for taking the conversation upstream!
