### ISSUE TITLE
Small arrow in disabled combo box

### ISSUE THREAD

**Issue by lenemter** [elementary/stylesheet#1216]
### What Happened?

Enabled combo box:
![image](https://user-images.githubusercontent.com/80143868/180780850-8905667e-4ff5-4ace-85f6-c5adbbdb27c0.png)
---
Disabled combo box:
![image](https://user-images.githubusercontent.com/80143868/180780929-e19c4c4f-2112-40f9-8ea6-1672c5bf5313.png)

### Steps to Reproduce

1. Open Calendar App
2. Click gear icon in headerbar
3. Edit Google calendar

### Expected Behavior

Icons should be the same

### OS Version

6.x (Odin)

### Software Version

Latest release (I have run all updates)

**Comment by danrabbit** [comment]
Yeah this seems to be a stylesheet issue: https://github.com/elementary/stylesheet/blob/ca8c59303763964e6423122c53b7f357acc1811e/src/gtk-3.0/widgets/_menus.scss#L35
