### ISSUE TITLE
No tab bar and full-width tabs (Terminal, Web and others)

### ISSUE THREAD

**Issue by Odi-3** [elementary/stylesheet#1239]
### Problem

Currently the tab bar is always present even when only one tab is open; furthermore, when there are 2 or more tabs they have a default width and do not cover the entire width of the bar itself.

### Proposal

The suggestion is to have a tab bar that appears only when there are at least 2 tabs open, making sure that the tabs occupy the entire available width. This would be consistent with a minimalist and modern style.

**Comment by danirabbit** [comment]
Hey thanks for your feedback! There is out of control of the stylesheet. Tab bar behavior is up to each app to implement, so issues would need to be filed against each affected app.

Closing as "Out of scope" since the stylesheet is not able to control tab bar behavior, only appearance

**Comment by Odi-3** [comment]
Sorry for the mistake
