### ISSUE TITLE
Styling of AdwMessageDialog

### ISSUE THREAD

**Issue by stan-janssen** [elementary/stylesheet#1251]
### What Happened?

The styling of browser dialogs does not fit with the rest of the OS as well as it used to. The latest version (44) looks like this:

![dialog-44](https://user-images.githubusercontent.com/12174852/229590607-7c6525f5-0d1a-4480-9ccc-3d74bfb26131.png)

While the previous version looked like this:

![dialog-42](https://user-images.githubusercontent.com/12174852/229590583-cd1e8b98-00d4-4c68-9655-a3ccacc36806.png)

### Steps to Reproduce

Trigger a browser dialog in Web, for instance by attempting to close a page on which you have entered text, like a Github comment.

### Expected Behavior

The dialog should be like the other dialog boxes in the OS, like those from Files or Code.

### OS Version

7.x (Horus)

### Software Version

Compiled from git

**Comment by Exalm** [comment]
That's an AdwMessageDialog. It does _not_ share style with GtkMessageDialog, those have a rather annoying layout to work with, so it needs separate styles.

**Comment by danirabbit** [comment]
This was fixed in #1257
