### ISSUE TITLE
Window margins cause titlebar issues in Mutter 44

### ISSUE THREAD

**Issue by davidmhewitt** [elementary/stylesheet#1253]
In Mutter 44, X11 SSD titlebars run as a separate GTK 4 process. With our stylesheet, they look like this:

![image](https://user-images.githubusercontent.com/3372394/231400946-58820acc-9add-4579-a40a-0e3e03144c5a.png)

This is due to this margin in the stylesheet:

https://github.com/elementary/stylesheet/blob/0c841189a3ae0b06b7f5cf551d3d2c6266eda80e/src/gtk-4.0/widgets/_windows.scss#L8

If we remove this margin, it looks like this:

![image](https://user-images.githubusercontent.com/3372394/231401729-2daa3c93-0483-4d45-a292-37bf68e1710a.png)

Can we have a bit of an investigation into why we have a margin here when Adwaita doesn't, and whether it's needed with a view to removing it in the next release?

**Comment by Exalm** [comment]
That margin looks like it’s a gtk3-ism, since iirc 3 was using it to determine the invisible border size, while 4 doesn’t.

You also want to disable round corners for ssd windows, you can see the bottom corners are glitchy on that terminal.

**Comment by danirabbit** [comment]
Yup that's exactly it. It was a quirk to set the resize are. I'll do a branch :)
