### ISSUE TITLE
The frame of Gtk.Switch under the headerbar is shown

### ISSUE THREAD

**Issue by ryonakano** [elementary/stylesheet#1296]
### What Happened?

The frame of Gtk.Switch under the headerbar remains displayed like this:

![Screenshot from 2024-06-30 11-24-08](https://github.com/elementary/stylesheet/assets/26003928/05b60d1c-1607-453f-92a0-dbb101b815fc)

### Steps to Reproduce

1. Open System Settings
2. Go to Keyboard → Behavior
3. Shrink the window height so that we can scroll
4. Scroll to make some Gtk.Switch to be under the headerbar

### Expected Behavior

The frame of Gtk.Switch under the headerbar should not be shown.

### OS Version

8.x (Early Access)

### Software Version

Latest release (I have run all updates)

**Comment by danirabbit** [comment]
I've seen this on my desktop but I can't reproduce it on my tablet. I'm thinking it's a graphics driver issue maybe or GTK issue. But either way not really anything I can do about it in stylesheet, sorry!
