### ISSUE TITLE
Support .flat headerbars 

### ISSUE THREAD

**Issue by Philip-Scott** [elementary/stylesheet#172]
Flat headerbars should have no bottom border, no gradient, and use the app's default background color

You should be able to do something like so by adding the .flat class:
![headerbar](https://user-images.githubusercontent.com/10786508/29231801-2dcbd5c0-7eae-11e7-9b38-4ed5ed809a20.png)

**Comment by danrabbit** [comment]
probably the way to do this is to change the `.default-decoration` class to include `.titlebar.flat` and then make a one-liner for `default-decoration` that only includes the padding change
