### ISSUE TITLE
User Accounts plug full name entry is very tall

### ISSUE THREAD

**Issue by codygarver** [elementary/stylesheet#173]
Wasn't like this on Loki, see attached screenshot.

![user-accounts-full-name-entry-tall](https://user-images.githubusercontent.com/2166391/29244410-fbc3d86e-7f7c-11e7-8c36-23c0a025054c.png)

**Comment by danrabbit** [comment]
There's no `max-height` property in Gtk.CSS so this has to be solved in the plug itself. Closing as `Invalid`
