### ISSUE TITLE
Light and dark text classes

### ISSUE THREAD

**Issue by cassidyjames** [elementary/stylesheet#186]
At least for the headerbar, so developers could just add a class as well as a brand color and not have to manually set the font color and shadows and everything.

**Comment by danrabbit** [comment]
I think we currently have `color-light` and `color-dark` as things. We should check what class GtkColorButton is using probably

**Comment by danrabbit** [comment]
Since you can tell a style context to use the dark style, I don't think we need this in the stylesheet
