### ISSUE TITLE
Add margin to entries in inline toolbars

### ISSUE THREAD

**Issue by cassidyjames** [elementary/stylesheet#192]
Came up at https://github.com/elementary/installer/pull/114

**Comment by cassidyjames** [comment]
![image](https://user-images.githubusercontent.com/611168/29889573-e11bc0fe-8d81-11e7-978e-a5d28f0be7ce.png)

**Comment by cassidyjames** [comment]
Pop! and Adwaita seem to have margins on their entries in inline toolbars as well (or at least on their entried generically, which affects them in inline toolbars) and this pattern looks a bit better there.

**Comment by danrabbit** [comment]
It looks like we don't actually use an inline toolbar here anymore, but they do have built-in padding in the new stylesheet, so I think this is fixed
