### ISSUE TITLE
FileChooserDialog should not inherit brand styling

### ISSUE THREAD

**Issue by donadigo** [elementary/stylesheet#199]
The `Gtk.FileChooserDialog` shouldn't inherit the `colorPrimary*` brand color properties set by the applications.

![screenshot from 2017-08-24 10 58 32](https://user-images.githubusercontent.com/3385679/29681002-3da31af0-88bb-11e7-8e2f-6e3181f9aac0.png)

Screenshot from https://github.com/donadigo/eddy/issues/37

**Comment by danrabbit** [comment]
Gonna close this since it'll be solved when the file chooser is a portal (and thus a separate process)
