### ISSUE TITLE
Windows leave very small gap to Wingpanel

### ISSUE THREAD

**Issue by capstan1** [elementary/stylesheet#201]
Since the last update (I think when rounded corners for maximized windows where introduced), maximized windows leave a small gap to the Wingpanel, showing some background.
![bildschirmfoto von 2017-09-10 14 31 06](https://user-images.githubusercontent.com/17147867/30249110-b6a48192-9634-11e7-80ca-fef29a43826d.png)

**Comment by danrabbit** [comment]
Can you confirm that this issue occurs with default settings and/or after restarting? It looks like you have some custom theming here

**Comment by capstan1** [comment]
You were totally right, it disappeared after restarting!
