### ISSUE TITLE
Fix Label Colors in Dark Applications

### ISSUE THREAD

**Issue by btd1337** [elementary/stylesheet#205]
Is it possible to correct the label colors, when mouse is hover, in dark applications?

Reproduction of the problem:

See the 'Single Click' label

Normal

![screenshot from 2017-09-17 12-33-31](https://user-images.githubusercontent.com/11943860/30522682-816fec2a-9baa-11e7-9572-4f6b370f6759.png)

and now, when mouse is over:

![screenshot from 2017-09-17 13-13-04](https://user-images.githubusercontent.com/11943860/30522724-163e1ed0-9bab-11e7-870d-029efeeb8688.png)

Bug: You can't see the label text.

**Comment by danrabbit** [comment]
This seems to be a bug in Eclipse which is trying (and failing) to imitate Gtk+ styles in whatever toolkit it uses.
