### ISSUE TITLE
Unreadable buttons over dark backgrounds in browsers

### ISSUE THREAD

**Issue by inad9300** [elementary/stylesheet#209]
Maybe they should get some background color, instead of being transparent...

![button-no-background](https://user-images.githubusercontent.com/3440331/30935346-b0cbd5aa-a3d0-11e7-90d8-6f85d81ca2cd.png)

**Comment by peteruithoven** [comment]
Might be interesting to compare it to the transparent fullscreen toggle button in Videos:
![screenshot from 2018-03-24 17 22 27](https://user-images.githubusercontent.com/523210/37866226-2e9355d8-2f88-11e8-9627-47f4b770835b.png)

**Comment by danrabbit** [comment]
Fixed in greenfield. Buttons now have a background by default
