### ISSUE TITLE
Document Viewer always has the "mouse over" effect on the "New Window" option

### ISSUE THREAD

**Issue by dcominottim** [elementary/stylesheet#212]
When opening Document Viewer and clicking on its icon on the top-right section of its window, the "New Window" option is always highlighted in spite of the actual position of the mouse:

![docviewer](https://user-images.githubusercontent.com/4914233/31474431-1b454cb2-aed1-11e7-9da4-4092d35dea6d.PNG)

**Comment by danrabbit** [comment]
I can't reproduce this any longer. I believe it's been fixed
