### ISSUE TITLE
Question regarding dark themes

### ISSUE THREAD

**Issue by febrezo** [elementary/stylesheet#217]
Do we have the chance of choosing between a global light theme (i. e., the classic one) and a global dark theme? Many of us may suffer from eye-stressing because of too bright screens and it may be nice to make this a system wide option to change the default behaviour globally. Just wondering if this is something that has been considered.

**Comment by snwh** [comment]
This is possible through `gsettings` but using the elementary stylesheet completely dark will not be the ideal experience: https://elementaryos.stackexchange.com/questions/4122/is-the-dark-theme-officially-supported
