### ISSUE TITLE
Offer a flatpak theme for this stylesheet

### ISSUE THREAD

**Issue by arshubham** [elementary/stylesheet#224]
Currently flatpak apps on elementary default to Adwaita whitch is disconnecting to the whole user experience. Even if moving forward elementary chooses to move to snaps, this should be available to the users. 

More Info: https://tingping.github.io/2017/05/11/flatpak-theming.html

**Comment by MrMarukesu** [comment]
I have a Manifest for the [icons](https://github.com/MrMarukesu/org.freedesktop.Platform.Icontheme.elementary) here, and the [stylesheet](https://github.com/MrMarukesu/org.gtk.Gtk3theme.elementary) here, but you need to recompile when you wanna update.

**Comment by arshubham** [comment]
@MrMarukesu  Can you share the build instructions for the theme. Never worked with flatpak-builder before ...

**Comment by MrMarukesu** [comment]
with the flatpak-builder installed, run:
`flatpak-builder BuildDirectory --repo=repo org.gtk.Gtk3theme.elmentary.json`
and after this succeed
`flatpak remote-add -no-gpg-verify --if-not-exists RepoName repo`
`flatpak install RepoName org.gtk.Gtk3theme.elmentary`
with repo and BuildDirectory begins any directory of your chose and RepoName any Name.

**Comment by MrMarukesu** [comment]
ok, now it's is in flahub repo. a simple ` flatpak install flathub org.gtk.Gt3theme.elemetary` gone to work.

**Comment by janxkoci** [comment]
All flatpak apps that I used in last half a year use elementary theme, so I think this can be closed.

But I have a question: could this be used also for **snap** apps? I have an issue with snap of Epiphany 3.32 (which is amazing release) where the background of searchbar/addressbar is transparent so I cannot see suggestions properly.

**Comment by GammaGames** [comment]
I think it would be nice to add an elementary-dark variant as well as the base light theme

**Comment by cassidyjames** [comment]
We'll provide the stylesheet inside the elementary SDK once that is ready, but for now, yes, there's an unofficial/community-maintained version on Flathub.
