### ISSUE TITLE
No visible scrollbar on Firefox

### ISSUE THREAD

**Issue by Suzamax** [elementary/stylesheet#231]
It does, however, have a little white/translucent border where the scrollbars are positioned (it works, so it's the scrollbar, but the scroll does not appear).

![captura realizada el 2017-11-16 17 08 15](https://user-images.githubusercontent.com/10341605/32901822-10182292-caf1-11e7-9ca0-fee08fcd71d1.png)

(Click the image in Firefox to see the white border on the bottom and right side)

Browser is newest Firefox, so Firefox 57 and above is affected.

**Comment by Astro-City** [comment]
Hi.  

I noticed the same thing, but when i tried Ubuntu 17.10 i saw the same issue. It seems that is not an Elementary OS problem.

You can see it clearly when you remove all the functions (search, top sites) from the new tab page and even if isn't anything to scroll, you still see the scroll bar without dark grey selector.

**Comment by danrabbit** [comment]
There's nothing in our stylesheet that provides specific styles for Firefox. This must be a problem with Firefox's interpretation of Gtk styles. Closing since this does not effect native Gtk+ apps
