### ISSUE TITLE
Wingpanel style when windows are maximized

### ISSUE THREAD

**Issue by casasfernando** [elementary/stylesheet#232]
Would you consider changing Wingpanel style when windows are maximized from solid black to something different or even the same black but add some transparency?
I believe solid black doesn't play well with some indicators that use dark colours.
I changed the stylesheet and left the panel black but added 0.6 transparency and now all my indicators are perfectly visible and it looks much better (less contrast than just black and white).
Maybe just adding transparency is not the best solution, but it is just an idea. I'm sure Elementary designers may have a better one to make it look right with the rest of the OS.

If you believe making such a change is not a good idea (for all users I mean, since I understand everyone is different), would you consider make this configurable by the user (for example to set transparency).

Thanks in advance.

**Comment by casasfernando** [comment]
![screenshot from 2017-11-16 18 48 36](https://user-images.githubusercontent.com/15861819/32906956-cc0420b6-cafe-11e7-8c40-746ded88549d.png)

This is sample of how it looks with the change I made.

**Comment by danrabbit** [comment]
Indicators shouldn't be using black or custom colors. They should be using symbolic icons and system style classes for colors so that they adapt properly with panel color changes.

Closing as "won't fix" since this is a bug with a third party indicator

**Comment by casasfernando** [comment]
Thanks for the quick reply.
