### ISSUE TITLE
Boxes with values. Arrows should have a more pronounced color so that you know when the limit have been reached.

### ISSUE THREAD

**Issue by Astro-City** [elementary/stylesheet#234]
Hi.

I first saw this problem on Gparted, but Libreoffice also seems to have this issue.  

If you try to make or edit a partition on Gparted. The value boxes have an increase and decrease arrows. When the value limit is reached is reached, the arrow turns just a little bit lighter than the normal one.  

I think this arrows design should change so we can distinguish better if we can't increase or decrease a value.

**Comment by danrabbit** [comment]
It seems in our quest to increase the contrast of text, we bungled this one. Since insensitive items are "incidental" UI elements, they don't necessarily need to pass contrast check

**Comment by Astro-City** [comment]
Thanks.

**Comment by danrabbit** [comment]
This should be fixed in master
