### ISSUE TITLE
Gray "All Settings" button and others almost looks like it's "unavailable"

### ISSUE THREAD

**Issue by D0J0P** [elementary/stylesheet#238]
If you go into the system settings, click on a setting, you'll see the gray "All Settings" button, and it's gray text looks "unavailable" like grayed out text and buttons normally appear. You'll also notice the same appearance with the sort by view buttons on Files.

I had to look very close to see some contrast, but it's not visible that it's a different color than the header bar, and is also the same color as the search bar in the settings where "All Settings" appears, but the search bar IS unavailable, while the "All Settings" button is not.

I feel like Luna was just a little bit better in this regard where the sort by view buttons on Files had a different color than the header bar, and made it obvious that they were available buttons.

**Comment by danrabbit** [comment]
Gonna close this since buttons have a background color now
