### ISSUE TITLE
Menus check sign. White on light grey is not visible.

### ISSUE THREAD

**Issue by Astro-City** [elementary/stylesheet#240]
Hi.  

I encountered this issue on Libreoffice, but is possible that it happens on more applications.  

I if you select an option on menu (like the side bar), the way that you know that is activated is through a check sign.  

On Elementary the check sign is white and if you hover with mouse it turns black with the background blue (highlight)

Since the menus background is light grey, this makes it hard to know when an option is activated or not.

**Comment by danrabbit** [comment]
Closing since LibreOffice is not a native Gtk+ app. This is likely an issue with their Gtk drawing emulation. Checkmarks in menus appear properly in native apps.

**Comment by tintou** [comment]
This issue will be fixed in next version, this bug probably comes from LibreOffice using Gtk2 in Loki
