### ISSUE TITLE
Split out elementary logos into their own repository/package

### ISSUE THREAD

**Issue by Conan-Kudo** [elementary/stylesheet#247]
If one doesn't take care to fix this downstream, it's entirely possible to unintentionally use the elementary logo in places they shouldn't be used.

To avoid this, the elementary logos should be removed from this repository and put into their own overlay package that elementary OS uses. That way, when the theme is packaged, the logo doesn't get included unless someone deliberately adds it.

**Comment by cassidyjames** [comment]
Moved to the icons repo
