### ISSUE TITLE
Firefox's contrast in buttons and their text

### ISSUE THREAD

**Issue by ajitid** [elementary/stylesheet#258]
![screenshot from 2018-01-17 10-05-06](https://user-images.githubusercontent.com/26769888/35026012-8db7664c-fb6e-11e7-8c3a-24379a022f60.png)

![screenshot from 2018-01-17 10-05-06 01](https://user-images.githubusercontent.com/26769888/35026016-90abff3e-fb6e-11e7-900f-50de22753ac4.png)

**Comment by arshubham** [comment]
Still affects Juno beta 1 with Firefox nightly 63. Looks fine on Adwaita 
![image](https://user-images.githubusercontent.com/14235191/42494886-2250b3ae-843f-11e8-98fa-4199531afe4e.png)

**Comment by Blast-City** [comment]
This also happens on the Firefox in now fullscreen exit box.

**Comment by danrabbit** [comment]
Gonna close because buttons in greenfield now always have a background color
