### ISSUE TITLE
Low contrast between enabled and disabled symbolic icon buttons

### ISSUE THREAD

**Issue by cassidyjames** [elementary/stylesheet#266]
I *think* this is generalizable, if not, my bad. @Philosoft reported on Code that the enabled and disabled arrows in the find bar are nearly indistinguishable, and I agree.

From https://github.com/elementary/code/issues/331:

>### How to reproduce
>
>1. Open any file
>1. Search anything
>1. try to guess does there are any matches above or below of visible content
>
>Related screenshot: 
>![scraatch-blur](https://user-images.githubusercontent.com/296326/35802173-160f214a-0a80-11e8-8ab9-c4fe11318627.png)
>
>On screenshot above: there are several matches below and none above visible content, but I can't deduce it from color of arrows or any visible message/status line. And status line is not an ultimate answer to this issue. It's frustrating.

–@Philosoft

**Comment by danrabbit** [comment]
Yeah I think the mistake here is that currently `:disabled` images and labels both use the same style. Contrast against the background was increased for the labels to keep them legible, but this means contrast between normal and `:disabled` images is not high enough to be useful.
