### ISSUE TITLE
Make sure we don't use px for font size

### ISSUE THREAD

**Issue by danrabbit** [elementary/stylesheet#279]
Specifying fonts in pt or em scales with a11y settings, but px are constant.

I'm not sure if we actually do this, this is just more of a check to make sure we're not

**Comment by cassidyjames** [comment]
@danrabbit I think this could be part of the same issue: also don't use px for any other sizes that we actually want to be relative to the font size. For example, do we actually want button padding to be in px, or do we want it proportional to the font? 

Making it proportional to the font can make the large-text accessibility option fell less janky, but also makes the entire UI take up more space.

**Comment by danrabbit** [comment]
Hm yeah that's an interesting point. It could make scaling look way more proportional, but I think that's probably worth a separate issue since it would be a much larger task

**Comment by danrabbit** [comment]
Looks like the only place px is used is in the emoji picker which is on purpose because we replace them with icons :+1:
