### ISSUE TITLE
Don't use px for proportional widgets

### ISSUE THREAD

**Issue by cassidyjames** [elementary/stylesheet#280]
Related to #279. Don't use px for any other UI sizes that we _actually_ want to be relative to the font size. For example, do we actually want button padding to be in px, or do we want it proportional to the font?

Making it proportional to the font can make the large-text accessibility option fell less janky, but also makes the entire UI take up more space. So it's something to consider throughout the stylesheet.

**Comment by danrabbit** [comment]
I'd definitely like to get some feedback from people using this a11y setting to find out if this is actually what they expect to happen. My concern is that for people with low vision this might mean losing a lot of real estate to UI chrome, even though it would make everything look a lot more proportional

**Comment by tintou** [comment]
Someone to reach probably here (Samuel Thibault) https://mail.gnome.org/archives/gtk-devel-list/2018-March/msg00001.html

**Comment by cassidyjames** [comment]
@danrabbit another interesting implication of this would be if we added a _smaller_ text option, it could be a better experience than trying to set some less-than-one noninteger scaling factor.

**Comment by danrabbit** [comment]
Closing because we're doing this in master now
