### ISSUE TITLE
Set dialog action area margin

### ISSUE THREAD

**Issue by danrabbit** [elementary/stylesheet#281]
`get_action_area` is deprecated in Gtk.Dialog and what we're currently using that for is to set margins. Since we can do that in CSS now, we probably should anyways and then we can fix this deprecation warning in all of our dialogs.

The painful thing is that this affects literally every dialog. Luckily we've ported a lot of dialogs to Granite.MessageDialog which should save some pain, but there are still many many other dialogs :(

There are a couple of style classes here: `dialog-action-box` and `dialog-action-area`

**Comment by cassidyjames** [comment]
@danrabbit we should probably create an org-level project to track the dialog issues, then?

**Comment by danrabbit** [comment]
Yeah that could be helpful to keep track
