### ISSUE TITLE
theme problem with firefox CSD

### ISSUE THREAD

**Issue by ho3ein-mola** [elementary/stylesheet#284]
!["test"](https://i.imgur.com/zH7KzmJ.png)

### its should be like this

!["test"](https://www.omgubuntu.co.uk/wp-content/uploads/2018/02/firefox-csd-in-ubuntu-17.10.jpg)

**Comment by MrMarukesu** [comment]
here with the nightly flatpak of firefox the CSD is fine, minus the button placement
![firefoxcsd](https://user-images.githubusercontent.com/21296444/37545446-9f7adb78-2947-11e8-882d-f96b828a682d.png)

**Comment by ho3ein-mola** [comment]
I installed Firefox 59 from main repository so its stable , maybe its Firefox problem .

**Comment by cassidyjames** [comment]
We don't control or special case for Firefox, so there's nothing we can do in this repo.
