### ISSUE TITLE
[$50] Menus have a duplicate bottom box shadow

### ISSUE THREAD

**Issue by danrabbit** [elementary/stylesheet#29]
This is especially apparent in the dark stylesheet

![screenshot from 2016-09-24 11 02 43](https://cloud.githubusercontent.com/assets/7277719/18810260/8ce29086-8246-11e6-91f3-b15fd076e9ee.png)
##

**Comment by codygarver** [comment]
There is a bounty for this issue [on Bountysource](https://www.bountysource.com/issues/37992764-menus-have-a-duplicate-bottom-box-shadow).

**Comment by danrabbit** [comment]
This must have been a bug in Gtk, because I can't reproduce it in 3.22
