### ISSUE TITLE
GtkSearchEntry fields are too high

### ISSUE THREAD

**Issue by fabiozaramella** [elementary/stylesheet#292]
![schermata del 2018-03-16 22 29 20](https://user-images.githubusercontent.com/5459945/37545880-cabd47f8-296a-11e8-8bb5-d1787788c3b5.png)

**Comment by danrabbit** [comment]
I unfortunately can't control this from CSS. The default for Gtk.Widget is `Gtk.Align.FILL` and there's no `max-height` property in Gtk.CSS. This would need to be fixed application side

Closing as "Out of Scope"
