### ISSUE TITLE
Libreoffice Stylesheet (GTK3)

### ISSUE THREAD

**Issue by giovannicaligaris** [elementary/stylesheet#295]
There's a white box on the right corner where the X is and it does not fit with the rest of the theme. 

![screenshot from 2018-03-17 23 42 59](https://user-images.githubusercontent.com/26255347/37561085-5366674c-2a3d-11e8-8be5-7689ac79c3c4.png)

Also, and this is a personal taste. In libreoffice-gtk3 there's too much white in the page area in Writer and also in the "Tools -> Options". It's a bit uncomfortable to the eyes. The gtk2 theme fits a bit better in this case.

Other than, everything else looks fine. Good job

I am having both of this issues in Loki and Juno.

**Comment by cassidyjames** [comment]
We don't control the LibreOffice GTK emulation, and we don't special case in the stylesheet for apps. Due to this, there's nothing we can do to fix this in this repository.

**Comment by fitojb** [comment]
Can you please file this issue [upstream](https://bugs.documentfoundation.org)? Be sure to mark it as `Blocks: 103182` to ensure the proper people gets notified.
