### ISSUE TITLE
[$50] Insensitive combo boxes are not obvious

### ISSUE THREAD

**Issue by danrabbit** [elementary/stylesheet#3]
![screenshot from 2015-09-22 07-56-12](https://cloud.githubusercontent.com/assets/7277719/18422285/8975347e-784d-11e6-96a4-99edfa7ff1cd.png)
##

**Comment by codygarver** [comment]
There is a bounty for this issue [on Bountysource](https://www.bountysource.com/issues/37780149-insensitive-combo-boxes-are-not-obvious).
