### ISSUE TITLE
Improve titlebar contrast

### ISSUE THREAD

**Issue by jwinnie** [elementary/stylesheet#319]
The text on the title bar should be darker to improve contrast:
![image](https://user-images.githubusercontent.com/20506149/39338720-72a6dbb8-4979-11e8-92af-33e5c09ba234.png)
![image](https://user-images.githubusercontent.com/20506149/39338735-8ea97816-4979-11e8-8e53-f8ea7de34781.png)

**Comment by danrabbit** [comment]
Already addressed in master :)

![screenshot from 2018-04-26 17 50 35 2x](https://user-images.githubusercontent.com/7277719/39338854-591c0b04-497a-11e8-9b96-1cdd1a8e9bc1.png)

**Comment by jwinnie** [comment]
Thank you :)
