### ISSUE TITLE
Menu-bar in dark theme not quite dark

### ISSUE THREAD

**Issue by WoodyWoodsta** [elementary/stylesheet#32]
The menu-bar (I stand to be corrected for the name of this UI element) doesn't match the dark theme and it becomes fairly out of place for apps that have a dark palette.

![screenshot from 2016-09-27 21 46 22](https://cloud.githubusercontent.com/assets/8268040/18889161/edfba7ec-84fb-11e6-9d26-0ecfe21809bc.png)

I'd love to fix it, however, I'm not too clued up on the layout naming of elementary's theming (and of GTK/metacity in general really). Some pointers would be great :+1:

**Comment by danrabbit** [comment]
Hm can't confirm this one. OP are you sure this app is requesting the dark stylesheet and it's a Gtk3 app?

![screenshot from 2016-09-27 12 52 14](https://cloud.githubusercontent.com/assets/7277719/18889308/3bde0a9a-84b1-11e6-8420-2eb914587876.png)

**Comment by WoodyWoodsta** [comment]
Confirmed it's not a GTK3 app (Electron). I don't seem to have _any_ GTK3 apps to confirm (fresh OS install), but now that I have learnt that GTK2 apps do not support dark variants, I understand it's not an issue for here. Will wait patiently for Electron/chromium to get going with GTK3 :+1:
