### ISSUE TITLE
Space between items in wingpanel

### ISSUE THREAD

**Issue by hochopepa-codes** [elementary/stylesheet#33]
Hi!
I really enjoy using elementary OS, design is very much refreshing. I would like make some modifications, but don't know where should I look. The space between items in "tray" is very big without reason. 

![selection_007](https://cloud.githubusercontent.com/assets/8946984/19022570/69d988b0-88db-11e6-9aa5-9003fe27bf92.png)

How can I change that? (what .css file and where should I change padding/margin?)
 Thanks!

**Comment by danrabbit** [comment]
The padding comes from `.menubar .menuitem`, but you can override it specifically for the panel with `.panel .menubar .menuitem`

**Comment by hochopepa-codes** [comment]
Thank you very much! I didn't know where could I post this, so I placed it here, sorry if that was a problem.

**Comment by danrabbit** [comment]
no worries :)

**Comment by hochopepa-codes** [comment]
Worked like a charm :) thanks again!
