### ISSUE TITLE
Please add some BASIC style support for gnome apps

### ISSUE THREAD

**Issue by surajmandalcell** [elementary/stylesheet#339]
The new stylesheet(.22) totally ignores other apps except native elementary ones and standard elements from it. Please add some basic styles to them for the sake of usability because its really very disturbing to see these un-styled gnome titlebars and stuff in elementary OS. Breaks the overall experience :(  

![image](https://user-images.githubusercontent.com/11650177/40091254-2ea16090-58d4-11e8-897c-e8fdf5efea12.png)
![image](https://user-images.githubusercontent.com/11650177/40091278-563f6d18-58d4-11e8-9fd6-3aca1cc0132d.png)

**Comment by danrabbit** [comment]
Gonna close this since that's probably OP's issue. Feel free to reopen if that isn't the case

**Comment by surajmandalcell** [comment]
@danrabbit NO!, these are normal apps installed using apt-get install, nothing fancy. You can check the status yourself in juno environment on 18.04. No theming is being applied to gnome apps for some reason.

**Comment by surajmandalcell** [comment]
Well they are actually snap apps for some reason ubuntu now ships with default snap apps, gosh :/
![image](https://user-images.githubusercontent.com/11650177/40106230-d0649990-5912-11e8-9c11-3dd50c3ca39b.png)

**Comment by surajmandalcell** [comment]
@danrabbit yea thanks for the info. Hope they fix this soon
