### ISSUE TITLE
certain applications don't display correctly

### ISSUE THREAD

**Issue by pbirkbeck** [elementary/stylesheet#348]
![image](https://user-images.githubusercontent.com/9362318/42249843-4f9a869e-7ee2-11e8-91cb-812e5f889510.png)

Playonlinux window on elementary os juno shows transparent backround

**Comment by danrabbit** [comment]
The stylesheet definitely doesn't have any control over this. Your best bet would be to file an issue against PlayonLinux

Closing as "out of scope"

**Comment by giovannicaligaris** [comment]
I am having the same issue with two more apps.

![screenshot from 2018-07-12 11 29 22](https://user-images.githubusercontent.com/26255347/42643338-e9fe054a-85c6-11e8-9d4c-e39b1a736c41.png)
