### ISSUE TITLE
Plank items ordering in Juno

### ISSUE THREAD

**Issue by LvLs9** [elementary/stylesheet#349]
After logout Plank resets the sequence of items, that have been added manualy.

For example, _Telegram_ and _PyCharm_, that manualy installed in `~/.local/bin`. 
They has created desktop shortcuts in `~/.local/share/applications`.

Can I give you more information for solve this issue?

**Comment by surajmandalcell** [comment]
Happens to me in case of certain app icons, i put terminal and gnome-monitor app side by side in plank. It resets every-time which is kind of annoying :rage:  . I didn't investigate it through tho,

**Comment by danrabbit** [comment]
The stylesheet doesn't have any control over this. Please report this at bugs.launchpad.net/plank

Closing as "Out of scope" because this can't be fixed in this repository
