### ISSUE TITLE
[juno beta 1] Headerbar is too high when using subtitle

### ISSUE THREAD

**Issue by ztefn** [elementary/stylesheet#352]
I'm testing [Haguichi](https://github.com/ztefn/haguichi/tree/elementary) in Juno and noticed that the headerbar is much higher in Juno (first screenshot) than it was in Loki (second screenshot). Not only is the headerbar higher, but this also results in the (active) buttons being stretched vertically (connect and search button in the screenshot).

It seems to me this problem is related to the headerbars' [subtitle](https://valadoc.org/gtk+-3.0/Gtk.HeaderBar.subtitle.html) being used.
![Juno](https://user-images.githubusercontent.com/343442/42413427-09ae488c-8220-11e8-970e-8327abf00ab2.png)
![Loki](https://raw.githubusercontent.com/ztefn/haguichi/ffe20ae72792d3f3fed81ebf1be9ea1bb6efe43e/data/screenshots/1.png)
PS: Any suggestion on how to provide different application stylesheets for Juno and Loki to cover the API and syntax differences?

**Comment by cassidyjames** [comment]
@ztefn I'm not entirely sure of the correct way to fix this, but it looks like setting your buttons in the headerbar to `valign = GTK_ALIGN_CENTER` resolves the strange styling without affecting much else. By default headerbars expand to fit their children, and by default GTK+ widgets are set to `GTK_ALIGN_FILL`. So this should resolve it on both Loki and Juno, though ro be fair I've only tested it briefly on Juno.

**Comment by ztefn** [comment]
@cassidyjames Thanks for your suggested workaround! Applying `valign = GTK_ALIGN_CENTER` indeed appears to fix the weird looking buttons.

I do wonder why the stylesheet in Loki managed to keep the headerbar slim when using both title and subtitle and not in Juno. Fair change this layout difference is caused by some GTK+ API changes in 3.22. 

I can fix the ultra high headerbar locally in my app's stylesheet using `.titlebar {
  padding: 3px;
}` but off course that won't benefit other applications. Unfortunately, there doesn't seem to be any speudo-class to only match titlebars that have subtitles.

**Comment by ztefn** [comment]
Fixes applied to Haguichi itself are commits https://github.com/ztefn/haguichi/commit/b7f5b1c93e552cd2c2cbbe183ed6c15689fa5a62 and https://github.com/ztefn/haguichi/commit/c9f167568d04a3ea5678436b49465cacb6276de4 with the following results in three different states:

_Normal_
![headerbar-juno-normal](https://user-images.githubusercontent.com/343442/43677826-e0c14c22-9808-11e8-83e3-1a2980187335.png)

_Dark_
![headerbar-juno-dark](https://user-images.githubusercontent.com/343442/43677828-e50d853e-9808-11e8-8682-c8b730fdcc21.png)

I will close this issue now because the reserved space is apparently hard coded in to GTK itself: https://developer.gnome.org/gtk3/stable/GtkHeaderBar.html#GtkHeaderBar--has-subtitle
And without any CSS selectors to match headerbars with or without subtitle, there's not much else that can be done here.
