### ISSUE TITLE
A native style to bend Qt4 and Qt5 applications to look like they belong into Elementary OS

### ISSUE THREAD

**Issue by torikulhabib** [elementary/stylesheet#353]
A native style to bend Qt4 and Qt5 applications to look like they belong into Elementary OS

https://github.com/FedoraQt/adwaita-qt

**Comment by danrabbit** [comment]
elementary subscribes to a “one true development path” and specifically endorsing and building around a single toolkit is a very important part of that. Supporting additional toolkits is a scope of work that I really don’t want to get into.

Closing this as both a “design conflict” with elementary itself and “out of scope” for this particular repo
