### ISSUE TITLE
Qt apps theming+icons is broken 

### ISSUE THREAD

**Issue by uncertainquark** [elementary/stylesheet#356]
Qt apps (like Dolphin and Okular) have completely broken theming and missing icons in Juno Beta-1.
 
![screenshot from 2018-07-08 22-20-42](https://user-images.githubusercontent.com/22585732/42422066-6b1cca16-82fd-11e8-9334-6028e54b494e.png)

In Loki, while the theming was not as great as the GTK apps (understandably), it was still functional and okay looking. In Juno, it is rather completely unusable. Installing "breeze-icon-theme" doesn't help either.

If this is not the right place to report, please direct me to the correct project. :)

**Comment by jlnr** [comment]
Probably related to #353?

**Comment by jlnr** [comment]
There's also #353 which was just marked as out of scope.

Does this affect all Qt apps or just a subset (maybe Qt5 or KDE)? I was using [a technical Qt app recently](https://www.unified-automation.com/products/development-tools/uaexpert.html) and while HiDPI scaling didn't work, the app was usable.

**Comment by snwh** [comment]
As these are Qt apps, they will look "broken" on a GTK-based desktop without proper theming. As for the "missing" icons, this is likely due to the KDE/Plasma apps referring to KDE-specific icons and the elementary icon set does not include those.

Also closing due to the same reason as #353.
