### ISSUE TITLE
Notebook active tab is hard to recognize

### ISSUE THREAD

**Issue by medeotl** [elementary/stylesheet#360]
Notebook active tab doesn't stand out of the others tabs, see screenshot. 
It's really hard to recognize it.

![screenshot from 2018-07-21 18-08-45](https://user-images.githubusercontent.com/1864684/43037721-1f7e78de-8d11-11e8-93b8-94921373abd8.png)

**Comment by danrabbit** [comment]
Tabs have been redesigned so this should be fixed
