### ISSUE TITLE
fat headerbars / gtk+ apps

### ISSUE THREAD

**Issue by axelmeunier** [elementary/stylesheet#399]
Testing juno-beta2. Headerbars of "non-elementary" gtk+ apps that use csd decorations seem consistently very fat (tested on utility apps like gedit, evince, simple scan). Padding is bigger than in default apps.
It only happens in the non-maximized state though.
I think it is a different issue than [#52](https://github.com/elementary/stylesheet/issues/52) which is why I am opening.

![screenshot from 2018-09-22 10-52-53](https://user-images.githubusercontent.com/3244556/45916816-37fef000-be6c-11e8-996c-a04586815301.png)

**Comment by arshubham** [comment]
@axelmeunier  This might be due to elementary apps setting `headerbar.has_subtitle = false;` as it reserves some space in the headerbar if not set. Try reporting this to the particular app you find looks odd and doesn't need it.

**Comment by axelmeunier** [comment]
@arshubham If it is the case, then the problem is that some of these apps do actually use subtitles (at least evince and gedit do for example).

**Comment by cassidyjames** [comment]
The stylesheet does not and cannot control app contents or widget margins, and will adapt to fit the contents that are there. In this case, Gedit must have added widgets or set margins that elementary apps do not.

**Comment by ztefn** [comment]
Actually, even elementary apps that wishes to utilize subtitles will suffer from this issue. I know because I've been there #352. Workaround was to override (decrease) the padding of the titlebar for elementary stylesheet. It's far from ideal.

**Comment by janxkoci** [comment]
I don't understand how is this "Out of Scope" if it affects apps installed by default in elementary OS (e.g. evince). Somebody should really look into this.
