### ISSUE TITLE
interface faults when using zoomed fonts

### ISSUE THREAD

**Issue by ruby4c** [elementary/stylesheet#401]
i'm currently using [elementary os juno beta]. everything looks fine after installation. but after zooming the fonts with gnome-tweak-tool, some toggle button looks funny.
![screenshot from 2018-09-24 20-13-05](https://user-images.githubusercontent.com/33241282/45951848-ab089200-c037-11e8-866c-93c5f7b032a7.png)
![screenshot from 2018-09-24 20-13-08](https://user-images.githubusercontent.com/33241282/45951849-ab089200-c037-11e8-85b6-43fca5f50ec0.png)
![screenshot from 2018-09-24 20-22-46](https://user-images.githubusercontent.com/33241282/45951850-aba12880-c037-11e8-9095-9516971025fe.png)

however the button under the volume column still looks normal:
![screenshot from 2018-09-24 20-15-17](https://user-images.githubusercontent.com/33241282/45951918-e3a86b80-c037-11e8-919c-a9ad7a0196b4.png)

**Comment by ruby4c** [comment]
and icons in the setting can be difficult to align.

![screenshot from 2018-09-24 20-29-12](https://user-images.githubusercontent.com/33241282/45952236-e8b9ea80-c038-11e8-84ad-0530d4496c74.png)

**Comment by danrabbit** [comment]
None of these things can be addressed from the stylesheet. Please open individual issues against each project where the issue occurs.

Closing as "Out of scope" since the stylesheet can't affect widget alignment or expansion
