### ISSUE TITLE
Move spinbutton down button to the left

### ISSUE THREAD

**Issue by danrabbit** [elementary/stylesheet#412]
This can be done with horrific black magic. But should it?

![screenshot from 2018-10-02 10 25 06 2x](https://user-images.githubusercontent.com/7277719/46365481-8e6aec00-c62d-11e8-8d44-9b3e263dfce6.png)

**Comment by cassidyjames** [comment]
If it's crisp and clean, I am down to try it. We'd want to sit with it for a bit and make sure there aren't major issues in any first- or third-party apps.

**Comment by danrabbit** [comment]
Alright so it looks like this actually doesn't work because we need to be able to set that margin with like calc(100% - whatever) or something, but gtk doesn't like that and there's a shitload of warnings and yeah. So maybe can't do it.

**Comment by cassidyjames** [comment]
`float: left` :trollface:
