### ISSUE TITLE
ModeSwitch's backdrop has a darker "on" state

### ISSUE THREAD

**Issue by cassidyjames** [elementary/stylesheet#413]
Looks like we missed a state

**Comment by danrabbit** [comment]
I can't reproduce this. Screenshot for clarity?

**Comment by cassidyjames** [comment]
In Granite Demo.

Window Back-dropped:
 
![screenshot from 2018-10-02 13 33 18](https://user-images.githubusercontent.com/611168/46372220-c3843800-c647-11e8-9f59-e4a993e033fd.png)

Window Focused:

![screenshot from 2018-10-02 13 33 42](https://user-images.githubusercontent.com/611168/46372240-d1d25400-c647-11e8-9482-f7c70f4afa55.png)

**Comment by danrabbit** [comment]
AH. I see it.

**Comment by cassidyjames** [comment]
Versus the "off" position

backdrop:

![screenshot from 2018-10-02 13 34 48](https://user-images.githubusercontent.com/611168/46372309-03e3b600-c648-11e8-94c0-6fadf32ca567.png)

focus:

![screenshot from 2018-10-02 13 34 56](https://user-images.githubusercontent.com/611168/46372316-06dea680-c648-11e8-965e-02e92e23162b.png)
