### ISSUE TITLE
Scrollbar in Epiphany is different from other default apps

### ISSUE THREAD

**Issue by D0J0P** [elementary/stylesheet#422]
The look and behavior of the scrollbar in Epiphany is different from that of other default apps in elementary OS. I tried creating an issue in [Gnome's GitLab](https://gitlab.gnome.org/GNOME/epiphany/issues/559#note_348634) with full details, and was told to report it against elementary's theme.

One other behavior that isn't present in Ephiphany for eOS is the new blue overscroll glow.

**Comment by D0J0P** [comment]
Maybe move to os-patches repo if more appropriate.

**Comment by cassidyjames** [comment]
The overscroll isn't present in WebKitGTK, and there's nothing we can do about that. If I recall correctly, we also can't make the scrollbar expand in WebKit for some reason as well.

**Comment by Exalm** [comment]
> If I recall correctly, we also can't make the scrollbar expand in WebKit for some reason as well.

WebKit doesn't provide `:hover` pseudoclass for scrollbar when hovered, only `.hovering` style class. Adwaita uses `.hovering` here (and `.dragging` instead of `:active`), so it works.

While it can be fixed in WebKit, it would probably be a lot easier to just support `.hovering` in all the selectors that mention `scrollbar:hover` :)

**Comment by danrabbit** [comment]
It looks like Adwaita does a lot of weird inverted `:not` selectors to make Webkit happy :( https://github.com/GNOME/gtk/blob/master/gtk/theme/Adwaita/gtk-contained.css#L1047

**Comment by Exalm** [comment]
That's generated from scss. Also, gtk master is GTK 4. I tested it with these changes:

```diff
diff --git a/elementary/gtk-3.0/gtk-widgets.css b/elementary/gtk-3.0/gtk-widgets.css
--- a/elementary/gtk-3.0/gtk-widgets.css
+++ b/elementary/gtk-3.0/gtk-widgets.css
@@ -1887,7 +1887,8 @@ scrollbar {
     -GtkScrollbar-has-forward-stepper: false;
 }
 
-scrollbar:hover {
+scrollbar:hover,
+scrollbar.hovering {
     transition: all 200ms ease-in-out;
 }
 
@@ -1902,7 +1903,8 @@ scrollbar.horizontal slider {
     min-height: 3px;
 }
 
-scrollbar.horizontal:hover slider {
+scrollbar.horizontal:hover slider,
+scrollbar.horizontal.hovering slider {
     min-height: 8px;
 }
 
@@ -1911,7 +1913,8 @@ scrollbar.vertical slider {
     min-width: 3px;
 }
 
-scrollbar.vertical:hover slider {
+scrollbar.vertical:hover slider,
+scrollbar.vertical.hovering slider {
     min-width: 8px;
 }
 
@@ -1923,7 +1926,8 @@ scrollbar slider {
     transition: all 200ms ease-in-out;
 }
 
-scrollbar.overlay-indicator slider:hover {
+scrollbar.overlay-indicator slider:hover,
+scrollbar.overlay-indicator.hovering slider {
     border-radius: 20px;
 }
 
@@ -1935,11 +1939,13 @@ scrollbar.overlay-indicator trough {
     background-color: transparent;
 }
 
-scrollbar.overlay-indicator:hover trough {
+scrollbar.overlay-indicator:hover trough,
+scrollbar.overlay-indicator.hovering trough {
     background-color: alpha (#000, 0.1);
 }
 
-scrollbar:hover trough {
+scrollbar:hover trough,
+scrollbar.hovering trough {
     background-color: transparent;
     border-radius: 0;
 }
```
and it was enough for webkit.

**Comment by danrabbit** [comment]
@Exalm works for me! Thanks for that <3

**Comment by D0J0P** [comment]
That brings Epiphany one step closer to looking like a native eOS app!

**Comment by D0J0P** [comment]
Now that we're in Odin and there's a repo for the Epiphany browser, can this issue be reopened and transferred there? The scrollbar in Epiphany still looks different from other eOS apps, and doesn't behave the same way when hovering over it either.
