### ISSUE TITLE
Plus button has grey background on first open

### ISSUE THREAD

**Issue by D0J0P** [elementary/stylesheet#423]
In some places throughout the UI, wherever there is a plus button to add something, it'll sometimes have a gray background behind it. This only seems to happen in printer settings and the calendar reminder tabs.
![screenshot from 2018-10-18 10 18 35](https://user-images.githubusercontent.com/19495660/47161283-c2960c00-d2bf-11e8-82b6-d1d0888ec10e.png)
![screenshot from 2018-10-18 10 22 23](https://user-images.githubusercontent.com/19495660/47161295-c590fc80-d2bf-11e8-9d27-073faa92e069.png)

For calendar reminders, clicking on that button to add a new reminder and then deleting it seems to remove the background behind it. 

For printer settings, clicking "All Settings" and then clicking "Printers" again seems to remove the grey background behind the button. 

Other places in the UI, like Keyboard settings, don't have anything and look normal, but _does_ appear when you click on it and then click away. To remove it, you have to click away again. 
![screenshot from 2018-10-18 10 26 28](https://user-images.githubusercontent.com/19495660/47161572-4cde7000-d2c0-11e8-969e-c3f5319d2bff.png)

**Comment by cassidyjames** [comment]
This is just the focus style for those buttons, which is needed for accessibility. The specific plugs could focus something else if desired, but that would be outside the scope of this repository.

The actual style of focus should be addressed in master once we merge focus styles in general, so I can leave this open as an issue with the actual focus styling.
