### ISSUE TITLE
Some buttons with popovers have a gray background after clicked

### ISSUE THREAD

**Issue by D0J0P** [elementary/stylesheet#424]
In some areas, like Epiphany's "view open tabs" button, Music's EQ button, and mail's 3 dots button all seem to have a grey background after clicking it twice, and then goes away after you click somewhere else in the ui.
![screenshot from 2018-10-18 10 41 21](https://user-images.githubusercontent.com/19495660/47162975-08080880-d2c3-11e8-90c1-6a0487d63be9.png)
![screenshot from 2018-10-18 10 42 28](https://user-images.githubusercontent.com/19495660/47162976-08080880-d2c3-11e8-97b8-0631c815fc30.png)
![screenshot from 2018-10-18 10 43 26](https://user-images.githubusercontent.com/19495660/47162977-08080880-d2c3-11e8-9a93-4e26d897ea8c.png)

**Comment by danrabbit** [comment]
I'm going to close this as "Fixed" since we're now using accent color to indicate keyboard focus. It is intentionally that keyboard focus is indicated, but now it looks different from the checked state
