### ISSUE TITLE
Remove border from gtk menu button

### ISSUE THREAD

**Issue by arshubham** [elementary/stylesheet#427]
These are used in a lot of gnome apps and very out of place. They could be styled as buttons and used in all elementary apps.

![image](https://user-images.githubusercontent.com/14235191/47373353-49f0de80-d709-11e8-82cb-2ba972df836b.png)
![image](https://user-images.githubusercontent.com/14235191/47373366-5117ec80-d709-11e8-8c70-b429bfea89a5.png)

**Comment by cassidyjames** [comment]
I think this is no longer an issue in master? We support .raised buttons if that is a developer's intent, and headerbar buttons in general look a lot better across both elementary and GNOME apps.

**Comment by danrabbit** [comment]
I'm going to close this because we don't have any further information about how to reproduce this issue
