### ISSUE TITLE
Wingpanel is being overrided

### ISSUE THREAD

**Issue by pedrorls** [elementary/stylesheet#429]
Sometimes the wingpanel is being overrided by any other open window. 

![screenshot from 2018-10-24 12-21-43](https://user-images.githubusercontent.com/10673440/47442098-17d29180-d788-11e8-89c5-7bbadca9e4ba.png)

**Comment by arshubham** [comment]
Duplicate https://github.com/elementary/wingpanel/issues/130 . However haven't seen it for long time.

**Comment by pedrorls** [comment]
Ok! Didn't see! Thanks :)
