### ISSUE TITLE
Slider in music a little fuzzy on the left

### ISSUE THREAD

**Issue by D0J0P** [elementary/stylesheet#430]
The slider in music is a bit fuzzy on the corners of the left, where it's filled out, making it appear more square than the right side, which isn't filled out. As seen in press photo: 
![elementaryosmusicalbums](https://user-images.githubusercontent.com/19495660/47525620-b8e64880-d86b-11e8-8b1b-ab19d87d1c4f.png)

**Comment by danrabbit** [comment]
This appears to be resolved: 
![Screenshot from 2020-10-22 17 38 15](https://user-images.githubusercontent.com/7277719/96943566-673e1c00-148d-11eb-9d39-e4780f6c5a8f.png)
