### ISSUE TITLE
Round out progress bar

### ISSUE THREAD

**Issue by D0J0P** [elementary/stylesheet#431]
When you look at almost every corner of things in elementary os like windows, search bars, tabs, etc. they seem to have rounded corners. One glaring thing that doesn't have rounded corners are progress bars.
![screenshot from 2018-10-25 15 46 14](https://user-images.githubusercontent.com/19495660/47526512-f2b84e80-d86d-11e8-9452-365bcc98759e.png)

It might be nice to have them rounded off fully like some sliders in eOS:
![47525620-b8e64880-d86b-11e8-8b1b-ab19d87d1c4f](https://user-images.githubusercontent.com/19495660/47526682-783bfe80-d86e-11e8-9ffa-f792d26c9762.png)

![screenshot from 2018-10-25 15 58 21](https://user-images.githubusercontent.com/19495660/47526828-ef719280-d86e-11e8-8dba-1ff8ba1d8229.png)

Or at the very least, increase the border radius a little bit, kind of like search/address bar. The super square progress bar kind of sticks out in eOS, and it would be nice to round it out because of contour bias.

The only part I'm not sure about is the progress bar in Epiphany. That is squared off because it goes from one end of the browser window to the other.

**Comment by danrabbit** [comment]
I'm gonna close this since we now do have a slight corner radius in the new stylesheet
