### ISSUE TITLE
Evolution Mail Client - Colour of e-mail address and HTML links matches background.

### ISSUE THREAD

**Issue by HennieLouw** [elementary/stylesheet#436]
When using evolution mail client with Elementary OS Juno, the email addresses and any HTML hyperlinks are displayed in white text on white backgrounds. 

This makes the application exceptionally difficult to use and my research has shown that evolution uses the GTK theme to determine how it will display.

I've attached a screen capture of this happening.
![image](https://user-images.githubusercontent.com/7922123/47767204-b03bb980-dd26-11e8-9499-9ef242769dd5.png)

You'll notice that the highlighted from section shows the email address easily, but the non-highlighted section (the to: field) is white and almost impossible to read.

Some Details of my setup.
![image](https://user-images.githubusercontent.com/7922123/47767317-322be280-dd27-11e8-8c7a-99b624a342e3.png)
![image](https://user-images.githubusercontent.com/7922123/47767355-5f789080-dd27-11e8-8830-12015ede16ef.png)

**Comment by tintou** [comment]
This is unfortunately an issue in Evolution (see https://gitlab.gnome.org/GNOME/evolution/issues/207 )
A workaround is to add

```
    -GtkWidget-link-color: @link_color;
    -GtkWidget-visited-link-color: shade (@link_color, 0.8);
```

In the top of gtk-widgets.css inside of `* { … }`

**Comment by tintou** [comment]
According to the investigation of the Evolution developer, this is an issue with the elementary stylesheet.

He even made a small code to reproduce the issue easily and get more debugging information from the stylesheet.
https://gitlab.gnome.org/GNOME/evolution/issues/207#note_358000

**Comment by tintou** [comment]
So to have it work, we need something like:
```
*:link {
    color: @link_color;
}

*:visited {
    color: shade (@link_color, 0.8);
}
```
