### ISSUE TITLE
Switches are low-contrast in dark style

### ISSUE THREAD

**Issue by cassidyjames** [elementary/stylesheet#440]
Switches in the dark style are very low contrast and are pretty hard to see at both standard and mode-switch sizes.

![image](https://user-images.githubusercontent.com/611168/47945700-50c9df00-dec9-11e8-8f38-52630532f075.png)

**Comment by micahilbery** [comment]
![screenshot from 2018-11-02 22 55 16](https://user-images.githubusercontent.com/10608836/47947842-7e774e00-def2-11e8-861a-d81ee13685dc.png)

Maybe something similar to what we did with scales in the dark style would work here as well giving it more of a silver slider and background.

**Comment by cassidyjames** [comment]
@micahilbery that direction looks sane to me. It's much easier to see at a glance!
