### ISSUE TITLE
Popover's arrow border transparency issue

### ISSUE THREAD

**Issue by peteruithoven** [elementary/stylesheet#441]
I noticed on my HiDPI screen that the arrow on top of the PopOvers have a weird thick gray border, which is inconsistent with the rest of the PopOver.

![screenshot from 2018-11-07 14 58 38](https://user-images.githubusercontent.com/523210/48135601-a8879200-e29d-11e8-801f-aabf2512f92d.png)
![screenshot from 2018-11-07 14 59 58](https://user-images.githubusercontent.com/523210/48135652-d10f8c00-e29d-11e8-9b8b-e0086fd29a8b.png)

When I pick a different background color:
![screenshot from 2018-11-07 15 27 33](https://user-images.githubusercontent.com/523210/48137319-15049000-e2a2-11e8-88cf-6329cc1df898.png)
![screenshot from 2018-11-07 15 27 22](https://user-images.githubusercontent.com/523210/48137321-15049000-e2a2-11e8-9f2c-e1735e813a95.png)

For some reason, when taking the screenshot using "Screenshot of the current Window" the border is consistent. 
![screenshot from 2018-11-07 14 37 54](https://user-images.githubusercontent.com/523210/48135704-f7352c00-e29d-11e8-8988-ab6d1127fb5e.png)
![screenshot from 2018-11-07 15 01 26](https://user-images.githubusercontent.com/523210/48135776-2481da00-e29e-11e8-86c2-151b54d7e0c8.png)

Could this be a transparency inconsistency?

**Comment by peteruithoven** [comment]
Overriding the default popover styles, removing transparency and also gives a consistent color. 
```
popover,
popover.osd,
.popover,
.popover.osd {
    /*border: 1px solid alpha (#000, 0.3);*/
    border: 1px solid @SILVER_500;
}
```

![screenshot from 2018-11-07 18 09 15](https://user-images.githubusercontent.com/523210/48147751-53a54500-e2b8-11e8-8829-1e55458a05d6.png)
![screenshot from 2018-11-07 18 07 06](https://user-images.githubusercontent.com/523210/48147752-53a54500-e2b8-11e8-8c45-af1d2d503721.png)
![screenshot from 2018-11-07 18 06 47](https://user-images.githubusercontent.com/523210/48147753-53a54500-e2b8-11e8-8ed0-df53994331b4.png)

**Comment by peteruithoven** [comment]
Default:
![screenshot from 2018-11-07 18 53 09](https://user-images.githubusercontent.com/523210/48150244-67ec4080-e2be-11e8-9be6-2a45dbf4034c.png)
Removing the `box-shadow`:
![screenshot from 2018-11-07 18 48 57](https://user-images.githubusercontent.com/523210/48150054-edbbbc00-e2bd-11e8-9708-d7a7ceb0d912.png)
Removing the `background`:
![screenshot from 2018-11-07 18 50 57](https://user-images.githubusercontent.com/523210/48150123-1ba10080-e2be-11e8-974b-31b2e47a4948.png)

Looks like in the arrow the background is behind the border, causing a difference. ?

Should we open an issue against Gtk at this point?

**Comment by danrabbit** [comment]
Yes, this is because the arrow portion doesn't seem to respect `background-clip` and box-shadow doesn't  apply to the arrow. One or both needs to be done in Gtk+ to fix this

**Comment by peteruithoven** [comment]
Super simple demo: https://github.com/peteruithoven/popover-arrow-border-transparency

**Comment by peteruithoven** [comment]
I opened an issue in the Gtk issue queue: https://gitlab.gnome.org/GNOME/gtk/issues/1452
