### ISSUE TITLE
Switches not reversed in RTL

### ISSUE THREAD

**Issue by cassidyjames** [elementary/stylesheet#451]
I'm not sure if this is something we have control over, of if it'd need to be handled in GTK itself. But switches still point to the right for "enabled", even in RTL languages. Other platforms appear to reverse the switch direction to follow the language direction.

**Comment by cassidyjames** [comment]
Filed upstream in GTK itself, as the issue also appears in Adwaita. I'm not sure if we can still work around it in the stylesheet, though—I kind of doubt it since it's the interaction and not just the visuals, but I'll let @danrabbit or someone more experienced with GTK make that call.

https://gitlab.gnome.org/GNOME/gtk/issues/1489

**Comment by danrabbit** [comment]
Yeah, I feel like there might be some nasty dirty things we can try with negative margin, but I feel like it would break animations. Gonna close this and rely on Gtk+
