### ISSUE TITLE
Drop GTK2 theme

### ISSUE THREAD

**Issue by cassidyjames** [elementary/stylesheet#458]
Since we don't support GTK2 in any way, it's not HiDPI-aware, and the theme has become massively out of sync with the GTK3 stylesheet, I wonder if we should drop it? It would also make it more obvious when apps are attempting to use GTK2 styles/variables instead of GTK3.

**Comment by tintou** [comment]
Things to consider: GIMP & Inkscape being GTK2

**Comment by cassidyjames** [comment]
Other things to consider: up-to-date GIMP and Inkscape are distributed as Flatpaks, which don't use the system GTK2 stylesheet anyway. We don't actively support and haven't supported GTK2 for a few releases, I think it's time to let it die. Legacy apps should probably be sideloaded anyway.

**Comment by cassidyjames** [comment]
(I'm not hard set on dropping it today, but I think visually it is so outdated that it would make things more clear if we didn't pretend to support it anymore)

**Comment by danrabbit** [comment]
I'm in favor of dropping the Gtk2 style in 6.0 maybe. IIRC Inkscape master is now Gtk3. I'm not sure what the status is of GIMP there but I think they're doing their own built in styles anyways now

I agree that it would be better to use the fallback styling for Gtk2 then to use an unmaintained style. It's been like 8 years apps have had time to update to Gtk3. I'm ready to let go :+1:

**Comment by cassidyjames** [comment]
With Flatpak being the way forward with elementary OS and being supported in AppCenter, I think it's still reasonable to plan this for 6.0. If we don't ship a GTK2 theme, is there a way to explicitly fall back to the Adwaita one since it's kind of sort of maintained upstream at least?

**Comment by lainsce** [comment]
I think if there's no GTK2 custom theme it already fallbacks to Adwaita or Clearlooks depending of distro default.

**Comment by cassidyjames** [comment]
@lainsce in GTK2 it falls back to the completely unstyled GTK. GTK only shipped with Adwaita as the default style in GTK3.

**Comment by TingPing** [comment]
Just as a correction, there is no such thing as "unstyled", GTK2 defaults to the Raleigh theme, the common Flatpak builds patch GTK2 to default to Adwaita (or the respective Adwaita-dark) and distros may do the same.

**Comment by cassidyjames** [comment]
Another (another) point: Inkscape is GTK3 now, and GIMP is shipping an entirely custom theme instead of using a system GTK2 theme by default. And if you use the "system" one in a Flatpak, it is indeed Adwaita which is more well-supported.

Greenfield already doesn't carry any GTK2 styles, so this should be considered resolved in that project.
