### ISSUE TITLE
Epiphany Browser Poor performance and Bugs

### ISSUE THREAD

**Issue by LewisOdam** [elementary/stylesheet#475]

**Comment by LewisOdam** [comment]
While on Youtube, logged in and not logged in, both light and dark modes.

The screen flashes red and yellow when scrolling down while the comments section is loading. Also very poor performance once the comments section is loaded, and gradually gets poorer the further down you scroll, like its a cache issue or something.
Also, no option to play videos in HD, only a maximum of 480p is available. Firefox showing up to 4K on tested video.
This is a new set of issues since JUNO :) 
On Thinkpad x200 Core2Duo P8600 @ 2.4ghz. intel mobile 4 chipset. 6GB DDR3 Ram

![screenshot from 2019-02-07 04-28-15](https://user-images.githubusercontent.com/38348954/52390538-ce852400-2a90-11e9-9649-3a12b60fc5d5.png)

![screenshot from 2019-02-07 04-13-29](https://user-images.githubusercontent.com/38348954/52390491-849c3e00-2a90-11e9-9ee1-4bcc5b4ced74.png)

**Comment by peteruithoven** [comment]
This is the repository for the elementary OS Stylesheet. 
Info on contributing to Epiphany:
https://gitlab.gnome.org/GNOME/epiphany/blob/master/CONTRIBUTING.md
