### ISSUE TITLE
Stylesheet for Web/Electron Js

### ISSUE THREAD

**Issue by 3x1l3** [elementary/stylesheet#480]
This isn't so much an issue as it is a question. Would it be possible to use these stylesheets for web development (more specifically for Electron JS)? I apologize if this isn't in the right spot

I'm looking to develop an application using Electron that has a native Elementary OS feel to it. I have found a repo for an existing port but it seems to be a few years out of date. 

If anyone could send me any resources and/or ideas to get started on this idea it would be greatly appreciated.

Thank you,

**Comment by cassidyjames** [comment]
Considering that elementary OS is strongly committed to native GTK applications, I don't see this as something we'd devote official resources to. The stylesheet hosted here is released under the GPL license and you're free to fork or adapt it to your own uses, but GTK and HTML—while both styleable via CSS—have very different implications.

**Comment by RMcNeely** [comment]
How much do you have the idea of including a package.json file in this repo so that [elementary/web-styles](https://GitHub.com/elementary/web-styles) can can include the sass files here instead of duplicating styles for the web?

**Comment by cassidyjames** [comment]
@RMcNeely yeah, web and GtkCSS are pretty different, especially when we want to support setting certain GtkCSS variables from within GTK apps. So I don't think it's worth trying to combine them.
