### ISSUE TITLE
Diffrent height of CSD

### ISSUE THREAD

**Issue by ivan-tretyak** [elementary/stylesheet#485]
![Screenshot from 2019-03-16 15-32-24](https://user-images.githubusercontent.com/34531674/54478444-42021a00-4823-11e9-978a-7dc684e43473.png)
If you include this design theme in the gnome, then differences in csd height and separator indent are visible in the csd feedreader

Distro: Fedora 29

**Comment by cassidyjames** [comment]
GTK widgets are inherently dynamically-sized based on their contents. The stylesheet does not control the contents of the app. If FeedReader were following the elementary HIG and using elementary-style controls, it would be the same size as other headerbars in elementary OS.
