### ISSUE TITLE
All corners rounded for all applications

### ISSUE THREAD

**Issue by ciampolo** [elementary/stylesheet#486]
Hello. I really want to make the permanent switch to Gala/Pantheon, it's wonderful thank you, though not having rounded corners (ie the visual inconsistency) is surprisingly really annoying.

I read https://github.com/elementary/stylesheet/issues/5 and wanted to ask whether it isn't possible to simply draw a 1px line inside every window during reparenting and then round that line instead of the actual widget? I doubt any window will draw content inside the edges 2px away that has relevancy (even statusbar items will always have couple pixel padding before any content is drawn). Though that would obviously mean the left over stuff of the window would have to be cut away which I don't know how hard/easy it is to do.

Also seeing https://github.com/alex47/KDE-Rounded-Corners it should technically be possible even without bad hacks though I don't know how hard it would be sorry I have no clue about graphics programming.

Notice how even videos have rounded corners with the mentioned extension. It's just vanilla mpv.

![round](https://user-images.githubusercontent.com/33424269/54864255-1c11d380-4d55-11e9-964f-edfb18e41824.png)

**Comment by cassidyjames** [comment]
We've tried this in the stylesheet, but apps can still draw outside of the rounded corner and we can't clip it. This would need to be implemented in the window manager, but then we couldn't get the nice borders and everything depending on the contents. So, ultimately, this is up to app developers to implement (and they can today by adding `.rounded` to their window and testing it!).
