### ISSUE TITLE
First tab in Files is missing left vertical line when not active

### ISSUE THREAD

**Issue by AwesomeAustn** [elementary/stylesheet#488]
When there are multiple tabs in Files and the first tab is not selected, the faint vertical line is not on the left. I think it should match the right most tab when not active.

![Screenshot from 2019-03-24 16-47-56](https://user-images.githubusercontent.com/6405444/54887866-e6ecaa80-4e54-11e9-88d1-f948649787e4.png)
![Screenshot from 2019-03-24 16-48-03](https://user-images.githubusercontent.com/6405444/54887870-ed7b2200-4e54-11e9-8594-8ad74a1a4f0e.png)

**Comment by danrabbit** [comment]
The design for tabs has changes so this is technically fixed
