### ISSUE TITLE
Installer looks completely broken. But functions perfectly.

### ISSUE THREAD

**Issue by aubreybourke** [elementary/stylesheet#492]
When installing Elementary OS from the live cd, the installer looks completely broken. However, it does function perfectly.

**Comment by peteruithoven** [comment]
Which is why elementary OS is working on a new installer: https://medium.com/elementaryos/meet-the-upcoming-installer-a499341218f5
This isn't something that can be solved with the elementary OS stylesheet.

**Comment by cassidyjames** [comment]
@aubreybourke could you expand on "completely broken," ideally with a screenshot or photo? I know Ubiquity isn't the prettiest of installers, but I don't believe it should look completely broken.

**Comment by aubreybourke** [comment]
I would have to reinstall the OS. And im not sure if the screenshot app is
even functional when installing.

In any case, the link in the previous post confirms that the developers are
aware of the problem. There are screenshots provided of the new installer.
And I must say it really does look great.

**Comment by danrabbit** [comment]
Closing since it seems that Ubiquity, while not very pretty, seems to look "as expected"
