### ISSUE TITLE
Non-flat destructive actions in inline-toolbars have red text on hover

### ISSUE THREAD

**Issue by mdalch** [elementary/stylesheet#496]
Hovering the mouse over "Empty the trash" button, changes the font's colour inside the button from white to dark red, meanwhile the background colour of the button is already red.

**Comment by jeremypw** [comment]
Color of text of "Empty the trash" button is also non-optimal when the Files window loses focus.

**Comment by KomalleanaByzantis** [comment]
I can corroborate both the original issue and that which @jeremypw mentions when the application loses focus. Here are my screenshots, if they are any help.

Focused and hovering the mouse above the button:
![Label on Empty the Rubbish Bin is sometimes difficult to read](https://user-images.githubusercontent.com/51057001/73567948-b491dd80-4467-11ea-878b-65a7d25ec627.png)

Defocused:
![Label on Empty the Rubbish Bin is sometimes difficult to read 2](https://user-images.githubusercontent.com/51057001/73567956-b8256480-4467-11ea-809f-124580ad6e35.png)
