### ISSUE TITLE
Add a way for apps to request rounded bottom corners 

### ISSUE THREAD

**Issue by danrabbit** [elementary/stylesheet#5]
Apps like Music and Calculator can have rounded corners because they have predictable widgets at the bottom.

We should do this via a class that allows apps to indicate they can be rounded instead of targeting specific apps in the stylesheet

**Comment by popenke** [comment]
Is this a global setting? 

Apps like Firefox or even the eOS Terminal will have rounded corners? Don't get me wrong, I love this feature, but having only some apps with rounded borders is weird.

**Comment by Defman21** [comment]
Every app has rounded corners for me.

**Comment by popenke** [comment]
All the four corners?

**Comment by Defman21** [comment]
Hmm, no. Never get attention to that :)

**Comment by danrabbit** [comment]
No it's not possible to do for every app, this is a style class that developers can invoke to apply a style to their app. It is not a setting, it is an API.
