### ISSUE TITLE
Popover has a border at the bottom when using dark style

### ISSUE THREAD

**Issue by hannesschulze** [elementary/stylesheet#501]
See the Granite SeekBar example - there's also a little border in light mode (value 96 vs 98), but there's too much when using the dark style I think (value 27 vs 33).

| Light | Dark |
| --- | --- |
| ![Screenshot von 2019-05-10 18 04 34](https://user-images.githubusercontent.com/43932053/57541527-81467600-734f-11e9-8a5a-61ce1faeb943.png) | ![Screenshot von 2019-05-10 18 04 33](https://user-images.githubusercontent.com/43932053/57541542-8c99a180-734f-11e9-8ae1-bb3801ee58d1.png) |

**Comment by jlnr** [comment]
Is this just a screenshot artifact or is the shadow really cut off at the bottom?

**Comment by hannesschulze** [comment]
It looks a little bit strange - but I just noticed this when setting the scale factor to 3.0

**Comment by danrabbit** [comment]
It's actually present in both, but harder to notice in the light stylesheet. I'm not sure what to do about this, actually. I would consider it a bug in Gtk.

I would say we could try to work around it, but we have no idea what direction the arrow will be on and there's no style class or pseudo class we could use to not have box shadow on a certain side.

**Comment by peteruithoven** [comment]
It's not the only issues with those arrows: https://github.com/elementary/stylesheet/issues/441
