### ISSUE TITLE
define a variable input_color

### ISSUE THREAD

**Issue by danrabbit** [elementary/stylesheet#502]
I'm thinking it would help with contrast to define a new variable `input_color`, especially in the dark style. It looks like some other designers typically are going much darker than the base color for inputs. This is the opposite case in the light style of course where we want to go whiter probably

Some reference material from Dribbble:

![shot_1299182179](https://user-images.githubusercontent.com/7277719/57549429-5a208200-7318-11e9-88e8-d5421975b116.png)
![toolbar](https://user-images.githubusercontent.com/7277719/57549430-5a208200-7318-11e9-83cc-c3774ae0ac06.png)

**Comment by cassidyjames** [comment]
@danrabbit just for entries, or for all inputs? In your first example there the radios are actually lighter than the background for higher contrast.

**Comment by danrabbit** [comment]
I'm gonna close this since we now have bg-color levels in Greenfield
