### ISSUE TITLE
DynamicNotebook: Padding and border around Gtk.EventBox

### ISSUE THREAD

**Issue by andreasfelix** [elementary/stylesheet#523]
Conversation from https://github.com/elementary/granite/pull/295:

---

@andreasfelix Definitely better than before! It still happens when I double-wheelclick on the border between two tabs, though. Do you think this is can/should be fixed within the same PR?

_Originally posted by @jlnr in https://github.com/elementary/granite/pull/295#issuecomment-508928380_

---

Unfortunately I think this is a different Issue. I have highlighted the size of the `GranitsWidgetsTab` and logged the enter and leave events:

![Border_event](https://user-images.githubusercontent.com/24651767/60758121-cb786a80-a013-11e9-92ac-4a067d5efc24.gif)

As one can see, the size of the `GranitsWidgetsTab` is slightly smaller than its visual size. This can also be seen at the event log: The signal get emitted when entering/leaving the blue highlighted area. When clicking on a Tab outside of this are, the signal gets directly passed to `DynamicNotebook` which leads to the restoring of the last closed tab.

I think this is related to the `padding` and `border` in the style sheet:

https://github.com/elementary/stylesheet/blob/ec23fec4a4bcd6577d2d2039eb24ae9bc9364577/elementary/gtk-3.0/gtk-widgets.css#L1670-L1688
Maybe it could be solved by changing `notebook tab` to `notebook tab widgets grid`, so the padding is within the `Gtk.EventBox`.

_Originally posted by @andreasfelix in https://github.com/elementary/granite/pull/295#issuecomment-508934896_

---

**Comment by andreasfelix** [comment]
I change the style in the Inspector and I think this would actually fix the problem. 

**Before:**
![Event_box_padding](https://user-images.githubusercontent.com/24651767/60761123-6a1bc000-a042-11e9-9d3d-be4211ca715b.gif)

**After:**
![GTK BOX](https://user-images.githubusercontent.com/24651767/60761121-68ea9300-a042-11e9-9246-0d94930a1480.gif)

**Comment by danirabbit** [comment]
Gonna close this since DynamicNotebook has been deprecated
