### ISSUE TITLE
contents of gtk-3.0/apps.css directly contradicts stated project purpose

### ISSUE THREAD

**Issue by decathorpe** [elementary/stylesheet#53]
from the README:
> The aim of style classes should be to be generic across applications. If an application needs a unique style, it should be bundled with that application.

This creates all kinds of issues when elementary apps are used with GTK themes other than this one (for example on distributions where the elementary theme is unavaible / broken due to the incompatibility with GTK3 > 3.18).

**Comment by danrabbit** [comment]
I don't think this is really a valid issue report as it doesn't contain any action items. There are some styles that may need to be moved into apps, but some of the style classes in this file are generic classes.
