### ISSUE TITLE
Combo box selected text moves when clicked

### ISSUE THREAD

**Issue by D0J0P** [elementary/stylesheet#531]
Not sure its the most elegant thing?

![Screen record from 2019-07-31 12 20 24](https://user-images.githubusercontent.com/19495660/62229524-d2ce3200-b38d-11e9-9527-909eb03fcd98.gif)

**Comment by danrabbit** [comment]
We don't really have control over where GTK spawns combobox menus. It looks like in GTK4, they spawn below the button completely.

Closing as "Out of scope" since this is more of a GTK issue
