### ISSUE TITLE
can't distinguish between focus/unfocus windows

### ISSUE THREAD

**Issue by megatux** [elementary/stylesheet#534]
One of the main functions of the WM is to make it easy for the user to show which window has focus, but I find very difficult coming from other WMs to know at a glance what window I'm working with.

Not sure if this is a Gala, or a [Gtk style](https://github.com/elementary/stylesheet/) thing, or both.
Let me add some examples:

Two windows with different border colors:
![Captura de pantalla de 2019-08-19 18-24-27](https://user-images.githubusercontent.com/850020/63300594-f01c5f00-c2ae-11e9-9ec7-68eaa8949cbe.png)
Which one has the focus? I usually use keyboard shortcuts but I mistakenly trigger it in the wrong app/window.

Two windows of VSCode (50%/50% positioned), a normal layout for working with projects:
![Captura de pantalla de 2019-08-19 17-52-56](https://user-images.githubusercontent.com/850020/63300569-e7c42400-c2ae-11e9-8038-d3f1cb19e585.png)

Two windows of Files app (50%/50% positioned):
![windows](https://user-images.githubusercontent.com/850020/63300571-e7c42400-c2ae-11e9-969d-cdd7341b60ef.png)

Do I have something broken? (Some time ago I tweaked the GTK settings.ini file but I cleaned it) or is this the _default_ style? I find it  _oddly broken_ .

**Comment by megatux** [comment]
Thanks for taking care & moving it Cassidy. For me, the Files example is not _super clear_, far from that. I have to put both windows side by side, focus my eyes and start comparing. A costly cognitive process, even with my _not-with-disabilities_ vision.
 
This is a sample with i3wm, default config. I think, it's always crystal clear what window I'm working with (has the input focus).

![Captura realizada el 2019-08-20 10 49 09](https://user-images.githubusercontent.com/850020/63361879-5654c080-c347-11e9-9e3d-342cd9dcf3c9.png)

![Captura realizada el 2019-08-20 10 48 48](https://user-images.githubusercontent.com/850020/63361881-5654c080-c347-11e9-9b7e-cf8253bc6c66.png)

For this reasons and other issues with alt-tab/win-tab/etc is that I moved away from Gala. I noticed I spend a lot of time "fighting with windows" in my workflow (as developer, for leisure I really like the complete Pantheon experience, it's just beautiful :heart_eyes: ).

I know CSD is the way elementaryOS moved, but ergonomics should go first and maybe we can use this ticket to identify existing issues and suggest potential enhancements, like the current split-screen proposals.

**Comment by danrabbit** [comment]
This should be more-or-less solved in Greenfield (as much as we can). We're now overlaying a gradient over the titlebar color so we can set a brighter backdrop gradient and the developer doesn't have to do any extra work.

But of course if a developer has custom decorations and they don't make a backdrop style, there's nothing we can do.
