### ISSUE TITLE
Add GtkPaned wide separator style

### ISSUE THREAD

**Issue by dcervenkov** [elementary/stylesheet#548]
## Prerequisites
- [x] I have searched open and closed issues for duplicates.

## Feature
**Is your feature request related to a problem? Please describe.**

As of Gtk+ 3.16, GtkPaned has a boolean setting whether to use wide separator: https://developer.gnome.org/gtk3/stable/GtkPaned.html#gtk-paned-set-wide-handle

Elementary theme does not define such a wide handle width, hence this setting has no effect.

E.g., Tilix has a "Use wide handle for splitters" option; see the difference when this setting works:

![Screenshot from 2019-09-30 14-01-45](https://user-images.githubusercontent.com/23052054/65877079-0b3cbd00-e38b-11e9-9561-9ca5f1133992.png)

![Screenshot from 2019-09-30 14-01-32](https://user-images.githubusercontent.com/23052054/65877088-0f68da80-e38b-11e9-92e2-b28763d3f06d.png)

**Describe the solution you'd like**

Please define distinct wide handle widths so that this option makes sense.

**Comment by cassidyjames** [comment]
@dcervenkov thanks for this! I think it's superseded by #551 though.
