### ISSUE TITLE
Scrollbars don't have a minimum size

### ISSUE THREAD

**Issue by gwutz** [elementary/stylesheet#55]
This is the current scrollbar. It isnt there at all and its nearly impossible to click it - 1px grab. 

![bildschirmfoto von 2017-01-23 12 28 10](https://cloud.githubusercontent.com/assets/373597/22202257/956d858c-e167-11e6-8b16-63e0b9b19b09.png)

The problem lies in my opinion on trough css definitions - they are not used in Adwaita. And we can now define slider-width with

```
slider {
    min-width: 2px;
}
```

**Comment by danrabbit** [comment]
I can't remove definitions because I need to keep compatibility with gtk 3.18, but @gwutz can you see if #57 fixes the issue?

**Comment by gwutz** [comment]
Now they are always 5px. The hover is not set. Relevant code (which would work) is

```
scrollbar slider {
 min-width: 2px;
 }

scrollbar slider:hover {
  min-width: 5px;
}
```
