### ISSUE TITLE
[$15] Extra Margin in GtkPaned

### ISSUE THREAD

**Issue by gwutz** [elementary/stylesheet#56]
Currently we get a Border around GtkPaned windows (8px right and bottom)

Relevant screenshot:
![bildschirmfoto von 2017-01-23 20 59 52](https://cloud.githubusercontent.com/assets/373597/22220469/24c4b560-e1af-11e6-9a6d-079ebd3dfd27.png)

This can be fixed if we remove that margin in gtk-widgets.css. But i have no idea what was the reason in the first place we defined it like that

**Comment by codygarver** [comment]
There is a bounty for this issue [on Bountysource](https://www.bountysource.com/issues/41252836-extra-margin-in-gtkpaned).
