### ISSUE TITLE
[$15] Active Tab not shown

### ISSUE THREAD

**Issue by gwutz** [elementary/stylesheet#58]
Tabs are not shown in Apps

Relevant Screenshot:

![bildschirmfoto von 2017-01-23 21 06 55](https://cloud.githubusercontent.com/assets/373597/22220731/28f7e1ce-e1b0-11e6-9cdb-5161d58c1435.png)

**Comment by danrabbit** [comment]
My guess is that this meas `notebook tab:active` is no longer a valid selector. Can you see if it has switched to `notebook tab:checked` possibly?

**Comment by gwutz** [comment]
Yes i can confirm, after setting the selector to checked, i can see the active tab but its not correctly styled. 

![bildschirmfoto von 2017-01-23 21 31 16](https://cloud.githubusercontent.com/assets/373597/22221435/52981cb2-e1b3-11e6-9239-1a0611df8ba3.png)

**Comment by danrabbit** [comment]
Oh very interesting! That definitely opens some doors for future styles. I'll make a PR in a moment

**Comment by codygarver** [comment]
There is a bounty for this issue [on Bountysource](https://www.bountysource.com/issues/41253111-active-tab-not-shown).
