### ISSUE TITLE
Accelerator labels unreadable when hovered with High Contrast theme

### ISSUE THREAD

**Issue by jeremypw** [elementary/stylesheet#588]
I have searched open and closed issues for duplicates.

## Describe the bug
If the High Contrast Gtk theme is used then hovering menuitems with AccelLabels renders those labels unreadable

### To Reproduce
1. Change the Gtk Theme to "High Contrast"
2. Open e.g. FIles or Terminal
3. Invoke a context menu with AccelLabels
4. Hover over items - the AccelLabels become unreadable (near zero contrast)

### Expected behavior
The labels remain readable (high contrast)

### Screenshots or screen recordings
![Screenshot from 2020-02-08 20 27 08](https://user-images.githubusercontent.com/10513844/74091646-7e7cdb00-4ab1-11ea-8938-8cdd8f2bfbe0.png)

## Platform Information
Hera 5.1 daily

**Comment by cassidyjames** [comment]
The high contrast theme is provided by Adwaita and we don't have any control over it from our stylesheet. I think this would be raised on the GTK issue tracker.

**Comment by jeremypw** [comment]
OK, I thought that may be the case.  Maybe an elementary high contrast theme is called for - or does our theme provide enough contrast for those with poorer eyesight already?

**Comment by jeremypw** [comment]
Incidentally, Nautilus accel labels are readable with High Contrast theme.
