### ISSUE TITLE
The translucid panel isn't working properly. the transparency is showing up on places it shouldn't.

### ISSUE THREAD

**Issue by wedsonlopes** [elementary/stylesheet#591]
![Screenshot from 2020-03-08 16-46-12](https://user-images.githubusercontent.com/35546352/76169983-7e2d3980-615c-11ea-9ec5-ed048cc16197.png)

**Comment by danrabbit** [comment]
OP, it doesn't appear that this window is actually maximized. See the icon in the top right corner
