### ISSUE TITLE
Add elementary-dark theme seperately for better integration with Flatpak

### ISSUE THREAD

**Issue by validatedev** [elementary/stylesheet#597]
## Prerequisites
- [x] I have searched open and closed issues for duplicates.

## Feature
**Is your feature request related to a problem? Please describe.**

Flatpak applications cannot able to use the dark variant of the elementary theme due to this issue: https://github.com/flathub/org.gtk.Gtk3theme.elementary/issues/5#issuecomment-603172258 , so I'd suggest that doing seperated elementary-dark theme is better choice for the Flatpak integration.

![Screenshot from 2020-03-24 14-55-25@2x](https://user-images.githubusercontent.com/29679552/77423071-a31ddf80-6ddf-11ea-9126-c43abef146f5.png)

**Describe the solution you'd like**

As I said, there should be extra elementary-dark theme, at least just for the Flatpak.

**Existing work**

Ubuntu's new Yaru theme has Yaru-dark and Yaru-light variants, also Adwaita Adwaita-dark

**Comment by cassidyjames** [comment]
The dark variant isn't currently intended to be general purpose and apply to all apps, so there aren't plans to package it as a separate stylesheet. Instead, apps can request a dark variant if they support it and in that case, it will use the dark variant.

Once a dark style preference is implemented, there might be a better way to request all apps use a dark style. But at the moment, I don't think we plan to package it up separately.
