### ISSUE TITLE
[$50] Weird selected row button highlight

### ISSUE THREAD

**Issue by danrabbit** [elementary/stylesheet#6]
There is a weird highlight on buttons that are on selected GtkListBoxRow, the structure looks like this:

GtkListBox
- GtkListBoxRow (selected)
  --- GtkButton

![problem](https://cloud.githubusercontent.com/assets/7277719/18422351/8f6e20ec-784e-11e6-81f0-277a28535f95.png)
##

**Comment by codygarver** [comment]
There is a bounty for this issue [on Bountysource](https://www.bountysource.com/issues/37780221-weird-selected-row-button-highlight).

**Comment by danrabbit** [comment]
I believe this was addressed in #45 

@codygarver do you have an example to the contrary?

**Comment by codygarver** [comment]
I can't reproduce this today, maybe it went away?

**Comment by danrabbit** [comment]
Gonna close since I believe this is fixed
