### ISSUE TITLE
[$15] Some HeaderBar Buttons show a background

### ISSUE THREAD

**Issue by gwutz** [elementary/stylesheet#60]
Some HeaderBar Buttons show a background - i think this are granite widgets but i am not sure.

Relevant Screenshot: 

![bildschirmfoto von 2017-01-23 21 39 19](https://cloud.githubusercontent.com/assets/373597/22221709/6a9a476c-e1b4-11e6-8f59-c7298a185ab7.png)

![bildschirmfoto von 2017-01-23 21 39 57](https://cloud.githubusercontent.com/assets/373597/22221738/852b4acc-e1b4-11e6-9f28-e5e4e682abc7.png)

**Comment by codygarver** [comment]
There is a bounty for this issue [on Bountysource](https://www.bountysource.com/issues/41254056-some-headerbar-buttons-show-a-background).
