### ISSUE TITLE
remmina keyboard indicator not visible in dark mode

### ISSUE THREAD

**Issue by ComputingFroggy** [elementary/stylesheet#602]
## Prerequisites
- [X] I have searched open and closed issues for duplicates.

## Describe the bug
When using remmina in elementary dark mode, it is not possible to see whether the keyboard indicator has been pushed or not.
Using another theme like HighContrast it is possible to see an indicator around remmina keyboard

### To Reproduce
1. switch elementary to dark mode Tweaks => prefer dark variant
2. launch remmina
3. click on the keyboard button
4. it is not possible if the button has been clicked or not.

### Expected behavior
usually the button is circled to see that it has been clicked

## Platform Information
<!--
 - OS: elementary Os
 - OS Version : Hera
 - Hardware info Intel i3-2120

- [X] I'm using the latest released stable version

**Comment by danrabbit** [comment]
You should expect to encounter issues when using Tweaks. Forcing a dark stylesheet is not supported for this reason. It seems that Remmina is also likely using Ayatana indicators, which are not supported.

Closing since OP is using an unsupported configuration
