### ISSUE TITLE
Black border around gtk applications

### ISSUE THREAD

**Issue by LinArcX** [elementary/stylesheet#603]
## Prerequisites
- [X ] I have searched open and closed issues for duplicates.

## Describe the bug
By installing this theme, i see black borders around [files](https://github.com/elementary/files), [calculator](https://github.com/elementary/calculator) and almost every other gtk-based appilcation.

### To Reproduce
1. Install io.elementary.stylesheet
2. Open a gtk-based app.(or elementary app)

### Expected behavior
This black border should be disappear.

### Screenshots or screen recordings
<img src="https://gist.githubusercontent.com/LinArcX/c8e9bc4eec041116639293abb011a9b0/raw/ef68650072ea834b483a74b3c0044f7e347a657b/Screenshot%2520from%25202020-04-05%252010-44-53.png"></img>

<img src="https://gist.githubusercontent.com/LinArcX/c8e9bc4eec041116639293abb011a9b0/raw/ef68650072ea834b483a74b3c0044f7e347a657b/Screenshot%2520from%25202020-04-05%252010-48-00.png"></img>

<img src="https://gist.githubusercontent.com/LinArcX/c8e9bc4eec041116639293abb011a9b0/raw/ef68650072ea834b483a74b3c0044f7e347a657b/Screenshot%2520from%25202020-04-05%252010-48-08.png"></img>

## Platform Information

- [ ] I'm using the latest version from git that I've manually compiled
- [X] I'm using the latest released stable version

## Additional context
I've also tried these solutions:
1- https://github.com/numixproject/numix-gtk-theme/issues/206#issuecomment-91518687
2- https://askubuntu.com/a/980761

And also tried to reset all `gsettings`:
`dconf reset -f / `

But still have this issue.

Hint: If i change the theme, this issue will gone. This is the result of using Raleigh theme:
<img src="https://gist.githubusercontent.com/LinArcX/c8e9bc4eec041116639293abb011a9b0/raw/4cd88035d646865ad56ef627618f3dff8b7b74ab/Screenshot%2520from%25202020-04-05%252011-01-47.png"></img>

**Comment by Anachron** [comment]
[This](https://github.com/numixproject/numix-gtk-theme/issues/206#issuecomment-91518687) should be a temporary fix.

**Comment by LinArcX** [comment]
[Solved](https://github.com/void-linux/void-packages/pull/20538#issuecomment-610416203)!
