### ISSUE TITLE
[$15] Menu Checkbox is not visible

### ISSUE THREAD

**Issue by gwutz** [elementary/stylesheet#61]
Plank Menus should show Menu Checkboxes for "stay in dock". But this is a generell problem

Relevant Screenshot:

![bildschirmfoto von 2017-01-23 21 43 41](https://cloud.githubusercontent.com/assets/373597/22221906/1c609776-e1b5-11e6-8850-4906833ea8dd.png)

**Comment by codygarver** [comment]
There is a bounty for this issue [on Bountysource](https://www.bountysource.com/issues/41254210-menu-checkbox-is-not-visible).
