### ISSUE TITLE
Switch doesnt highlight state

### ISSUE THREAD

**Issue by gwutz** [elementary/stylesheet#62]
The switch should show the active/not active state (i think with a blue background)

Relevant Screenshot: 

![bildschirmfoto von 2017-01-23 21 46 48](https://cloud.githubusercontent.com/assets/373597/22221991/79222eac-e1b5-11e6-91a6-3f4a49be56c9.png)

**Comment by wezm** [comment]
This needs to be reopened since the change was reverted in https://github.com/elementary/stylesheet/pull/85

**Comment by danrabbit** [comment]
The selector that works for 3.18 was reverted but the selector that works in 3.22 was not reverted (afaik)

**Comment by wezm** [comment]
Ahh, in that case 👍
