### ISSUE TITLE
Greenfield: occasional transparent/white text in light style

### ISSUE THREAD

**Issue by cassidyjames** [elementary/stylesheet#636]
I'm not sure if this is a GTK rendering issue, a stylesheet issue, an issue in the plug, or what. But in greenfield (only after the color branch was merged), opening System Settings → User Accounts while the default color scheme is active results in white/transparent text on a white background for me. Toggling the dark style on and off resolves it, so it looks like some weird GTK bug.

![image](https://user-images.githubusercontent.com/611168/81228659-a6de7d80-8fab-11ea-9fd1-e5d511956722.png)

Currently on Hera (bionic) fwiw.

**Comment by cassidyjames** [comment]
Okay, I'm also seeing this in GNOME Fonts (briefly on the main font preview, and reproducibly in the info view).

**Comment by danrabbit** [comment]
@cassidyjames still seeing this in fonts or closed?

**Comment by cassidyjames** [comment]
@danrabbit I'm still seeing it in views, I think. Yeah, Fonts still and AppCenter app descriptions, for example.
