### ISSUE TITLE
Warnings about changed selectors and missing units

### ISSUE THREAD

**Issue by gwutz** [elementary/stylesheet#64]
Gtk+ 3.22 changed some selectors and we get now warnings for them:
icon-shadow: is now -gtk-icon-shadow:
prelight is now hover
-gtk-image-effect is now -gtk-icon-effect
insensitive is now disabled

it is now mandatory to define a font in css.
```
.action-bar .title {
    font: Bold 11;
}
```
for example. A solution is to define:
```
.action-bar .title {
    font-weight: bold;
    font-size: 11pt;
}
```

**Comment by danrabbit** [comment]
These should be resolved now
