### ISSUE TITLE
Freeze Issue

### ISSUE THREAD

**Issue by Dhwanil20** [elementary/stylesheet#648]
Zoom Meeting and Skype Meeting time System Freeze

**Comment by cassidyjames** [comment]
This repo is for the system stylesheet, aka look and feel. Pretty sure it has nothing to do with non-native third-party proprietary software. :grimacing: If you can provide more details, we may be able to re-open the issue and move it to the appropriate repo.

**Comment by Dhwanil20** [comment]
Can you Please Help? how to Resolve this is Issue Because today same issue occur. Totally Freeze System then after forcefully shutdown and again start. how to send system log?

**Comment by Dhwanil20** [comment]
Today also Freeze App Store. I have search Visual studio Code after Os is Freeze
System:    Host: dhwanil-Inspiron-5575 Kernel: 5.3.0-51-generic x86_64 bits: 64 Desktop: Gnome
           Distro: elementary OS 5.1.4 Hera
Machine:   Device: laptop System: Dell product: Inspiron 5575 v: 1.3.3 serial: N/A
           Mobo: Dell model: 0DRVH0 v: X01 serial: N/A UEFI: Dell v: 1.3.3 date: 10/31/2019
Battery    BAT1: charge: 18.7 Wh 59.1% condition: 31.7/42.0 Wh (75%)
CPU:       Quad core AMD Ryzen 5 2500U with Radeon Vega Mobile Gfx (-MT-MCP-) speed/max: 1329/2000 MHz
Graphics:  Card: Advanced Micro Devices [AMD/ATI] Raven Ridge [Radeon Vega Series / Radeon Vega Mobile Series]
           Display Server: x11 (X.Org 1.20.5 ) drivers: ati,amdgpu (unloaded: modesetting,fbdev,vesa)
           Resolution: 1920x1080@60.05hz, 1360x768@60.02hz
           OpenGL: renderer: AMD RAVEN (DRM 3.33.0, 5.3.0-51-generic, LLVM 9.0.0) version: 4.5 Mesa 19.2.8
Network:   Card-1: Realtek RTL810xE PCI Express Fast Ethernet controller driver: r8169
           Card-2: Qualcomm Atheros QCA9377 802.11ac Wireless Network Adapter driver: ath10k_pci
           Card-3: Atheros
Drives:    HDD Total Size: 1512.3GB (0.5% used)
Info:      Processes: 280 Uptime: 59 min Memory: 2386.3/7664.2MB Client: Shell (bash) inxi: 2.3.56
