### ISSUE TITLE
Switches have darker accent then check/radios and progressbars

### ISSUE THREAD

**Issue by lainsce** [elementary/stylesheet#654]
Switches have a darker color than progressbars and check/radios
Is this correct?

![Screenshot from 2020-05-07 20 07 30](https://user-images.githubusercontent.com/4886639/81353085-8ba06a80-909e-11ea-83d6-05354d31216e.png)

**Comment by cassidyjames** [comment]
Yeah, I was wondering if we should use a darker shade for checkbuttons; right now the lighter accent colors are probably not contrast compliant, but color-buttons look like they are.

**Comment by lainsce** [comment]
Seems like a newer version of the stylesheet fixed this. Closing :)
