### ISSUE TITLE
Plank active indicators are black instead of chosen accent

### ISSUE THREAD

**Issue by lainsce** [elementary/stylesheet#659]
As seen on this screenshot:

![Screenshot from 2020-05-08 01 05 21](https://user-images.githubusercontent.com/4886639/81369124-02059280-90c8-11ea-8462-19e53885f87e.png)

**Comment by MrMarukesu** [comment]
plank get the indicator color from .background.selected:focus that doesn't exist in new stylesheet

**Comment by lainsce** [comment]
If the monochrome dots PR I have on the dock repo is merged, this will be fixed and wouldn't need stylesheet changes.

**Comment by lainsce** [comment]
Due to the initiative to remove the indicators, this became a non-issue. Closing.
