### ISSUE TITLE
Dark palette is too low-contrast

### ISSUE THREAD

**Issue by cassidyjames** [elementary/stylesheet#671]
We discussed this on Slack but I figured I'd report here so we don't lose track of it. It seems that the colors used in the dark palette, at least in `bg-color()`, are too low contrast. The end result is that all dark style widgets don't contrast from one another as much as the light style ones, at least perceptually. We could fix this by tweaking the values used by `bg-color`, or by tweaking the `BLACK` palette itself.

**Comment by fitojb** [comment]
Be sure to check the WCAG contrast guidelines :)

**Comment by danrabbit** [comment]
@micahilbery has been looking into reworking the black palette to ensure a consistent amount of contrast between levels. One issue he's come up against is how quickly it goes from being a "black" palette to a "grey" palette.

You can see his last revision here:

![Screenshot from 2020-05-22 10 23 37](https://user-images.githubusercontent.com/7277719/83425339-69baaf00-a3e2-11ea-8ac4-368cb1f45a11.png)

Haven't tried it in context yet, but it seems like we're either going to have to accept that the dark stylesheet is going to be lower contrast or it's going to be more of a dark grey theme than a black theme

**Comment by cassidyjames** [comment]
I am fine with it being a more contrasty dark gray, if that makes sense. I think contrast is more important than full-on darkness, especially because you can reduce some amount of brightness with the backlight, but you can't really turn up the contrast.
