### ISSUE TITLE
Gtk.StackSwitcher in a headerbar is missing border

### ISSUE THREAD

**Issue by ajcerejeira** [elementary/stylesheet#69]
Hi there, in Gtk applications that use StackSwitcher with icons, the apearance is quite odd, as you can see in the attachment, it misses the borders and the selected icon has a ellipsis around it. Perhaps it should look like Granite ModeButton? I don't know if this as to do with a proper Gtk style class or something...

Using Gtk.StackSwitcher:
![stack](https://cloud.githubusercontent.com/assets/22506305/22391900/08ecb2e4-e4ec-11e6-807a-76be8d20a498.png)

Granite.ModeButton:
![modal](https://cloud.githubusercontent.com/assets/22506305/22391897/04784cbe-e4ec-11e6-926c-2f0b0ab341fc.png)

Tested in **Elementary OS Loki 0.4 with GTK 3.18**

**Comment by danrabbit** [comment]
Ah yeah this is probably to do with how we deal with buttons in the toolbar in general. It should probably be handled by the `.linked` class, but I guess it wasn't.

Which app is pictured here? If I had a live example to mess with, it'd be easier to fix the issue :)

**Comment by ajcerejeira** [comment]
Exactly, despite the stack switcher uses the `.linked` class, when it comes to icons they are displayed that way. When the `Gtk.StackSwitcher` contains only text however the style is correctly implemented. The picture is just an example coded by me, to learn to use `Gtk.Stack`. Actually i don't know any apps that use `StackSwitcher` with icons (the majority of Gnome apps use the `Recent | Collections` text, which are rendered correctly). I was trying to achieve the functionality of `Granite.ModeButton` using a `Gtk.Stack`

Below is an example code where you can see the difference between two `Gtk.StackSwitcher`, one with icons and other without.

```vala
// Compile with --pkg gtk+-3.0
void main(string[] args) {
	Gtk.init (ref args);
	var window = new Gtk.Window ();
	var headerbar = new Gtk.HeaderBar ();

	// Create a stack whose two childs are simple labels
	var stack_icon = new Gtk.Stack ();
	var label1 = new Gtk.Label ("Icon:  Page 1");
	var label2 = new Gtk.Label ("Icon:  Page 2");

	stack_icon.add_named(label1, "page1");
	stack_icon.add_named(label2, "page2");

	// Assign to each label a icon
	stack_icon.child_set_property (label1, "icon-name", "view-grid-symbolic");
	stack_icon.child_set_property (label2, "icon-name", "view-list-symbolic");

	// Create the switcher, and add the style "linked"
	var switcher = new Gtk.StackSwitcher ();
	switcher.get_style_context ().add_class("linked");
	switcher.set_stack (stack_icon);

	// Create a new stack whose two childs are simple labels
	var stack_label = new Gtk.Stack ();
	stack_label.add_titled(new Gtk.Label ("Label: Page 1"), "Page 1", "Page 1");
	stack_label.add_titled(new Gtk.Label ("Label: Page 2"), "Page 2", "Page 2");

	// Create the switcher, with the class "linked"
	var switcher2 = new Gtk.StackSwitcher ();
	switcher2.get_style_context ().add_class("linked");
	switcher2.set_stack (stack_label);
	
	// Pack everything
	var box = new Gtk.Box (Gtk.Orientation.VERTICAL, 0);
	box.add(stack_icon);
	box.add(stack_label);

	headerbar.pack_start (switcher);
	headerbar.pack_start (switcher2);
	headerbar.show_close_button = true;

	window.add (box);

	window.set_titlebar (headerbar);
	window.destroy.connect(() => {
		Gtk.main_quit();
	}); 
	window.show_all ();

	Gtk.main ();
}
```

![captura de ecra de 2017-01-28 21 52 21](https://cloud.githubusercontent.com/assets/22506305/22400095/13023b7e-e5a4-11e6-82dd-313456642748.png)

**Comment by danrabbit** [comment]
@ajcerejeira the PR I just referenced should solve this. If you can comment on that PR, that would be great :)
