### ISSUE TITLE
Weird shadow at edge of headerbars/titlebars

### ISSUE THREAD

**Issue by cassidyjames** [elementary/stylesheet#696]
Look under the headerbar, at the very left- or right-most edge.

![Screenshot from 2020-05-14 15 59 03@2x](https://user-images.githubusercontent.com/611168/81990198-e9cbd100-95fb-11ea-8466-a673a9eb0068.png)

![Screenshot from 2020-05-14 15 58 24@2x](https://user-images.githubusercontent.com/611168/81990229-fb14dd80-95fb-11ea-9ca5-97ba72e9a421.png)

![Screenshot from 2020-05-14 15 58 15@2x](https://user-images.githubusercontent.com/611168/81990235-fd773780-95fb-11ea-9bad-86feab8813b0.png)

**Comment by hanaral** [comment]
Can confirm this is still a thing, does anyone know what actually causes this?
