### ISSUE TITLE
Linked navigation buttons in Epiphany are raised

### ISSUE THREAD

**Issue by cassidyjames** [elementary/stylesheet#697]
Due to #694. See https://github.com/elementary/stylesheet/pull/694#issuecomment-629442449

![Screenshot from 2020-05-15 13 35 33@2x](https://user-images.githubusercontent.com/611168/82103303-b22e5900-96cf-11ea-91a1-69bfeee7f326.png)

**Comment by danrabbit** [comment]
Turns out this was a bug in Epiphany. Resolved here: https://gitlab.gnome.org/GNOME/epiphany/-/commit/e0d96aebec8b3725a39ac71be4ac6355af7382b4
