### ISSUE TITLE
Dark mode

### ISSUE THREAD

**Issue by AethanFoot** [elementary/stylesheet#707]
When making gtk prefer dark variant not all windows adhere to this. For example the system settings windows stay in light mode which can be jarring when opening the app.

**Comment by Exalm** [comment]
that's intentional as the "dark mode" you're referring to is a hack. elementary will have a proper dark mode in future, and this is a part of the preparations: making default apps follow that instead of the hack.

**Comment by AethanFoot** [comment]
Thanks for the fast reply, look forward to seeing it as i love the whole design style of elementary
