### ISSUE TITLE
greenfield: spinner does not disappear on deactivate

### ISSUE THREAD

**Issue by davidmhewitt** [elementary/stylesheet#729]
Just spend ages trying to figure out why the spinner kept on spinning in AppCenter only to find it was a stylesheet issue :sweat_smile: 

It seems that when `stop` is called on the spinner or when `active` is set to `false` after a period of activity, it continues spinning and does not go invisible until some focus changes happens in the window.

This does not occur under Adwaita.

This may already be known but I thought I'd raise an issue because it's quite a subtle thing to miss as proven by me thinking AppCenter was broken.

**Comment by danrabbit** [comment]
@davidmhewitt are you still able to reproduce this? I can't seem to anymore

**Comment by davidmhewitt** [comment]
Yes, this appears to be resolved now
