### ISSUE TITLE
Inputs and buttons lack focus style

### ISSUE THREAD

**Issue by hanaral** [elementary/stylesheet#730]
The coloured outline and inset glow that input/selection fields and buttons had in the old stylesheet is not present in the new one.

**Comment by cassidyjames** [comment]
@hanaral known issue with the current stylesheet being very early and in development, but thanks for filing so we can track it here. :)

**Comment by hanaral** [comment]
@cassidyjames I think that the branch you made should probably just be merged so that it can just be iterated as time goes on.
It’s going to become a pain the more it gets postponed, due to all the changes that are ongoing
