### ISSUE TITLE
Destructive action button flahses when pressed in dark style

### ISSUE THREAD

**Issue by cassidyjames** [elementary/stylesheet#749]
I noticed in #741 but couldn't figure out what was causing it. I'm seeing a fast flash like between two states when clicking the destuctive action button in the dark style. It might also be in the light style but harder to spot. I'm wondering if it has something to do with transitions between states, and Gtk not executing those at the exact same time?

**Comment by okitoxo** [comment]
Is necesary apply transition for outline buttons when are focused?
This issue happens because button don't have an initial value for outline, animation on transition not work fine.
