### ISSUE TITLE
HdyWindow outside corners squared when tiled.

### ISSUE THREAD

**Issue by cassidyjames** [elementary/stylesheet#768]
Hm, it looks like there are still issues with Hdy windows even after #765. For example, Terminal's and Switchboard's (both HdyWindows) outside corners look like they're still squared when tiling, while AppCenter's and Epiphany's (not HdyWindows) are rounded. Mainly noticeable on the top outside corner—i.e. the top-left when tiling on the left, and the top-right when tiling on the right—since we're not masking that corner below the panel in Gala.

**Comment by danrabbit** [comment]
Sounds like this is actually a bug in Hdy. Alex is aware of it :)
