### ISSUE TITLE
New text-entry shadow is difficult to see on loDPI

### ISSUE THREAD

**Issue by hanaral** [elementary/stylesheet#773]
The inwards shadow that text entry boxes have is difficult to make out on lower resolution screens, especially when they are smaller. 
I suggest making them a pixel wider to make sure they have a bit more prominance, as right now I can barely tell its not just a gray line.

**Comment by danrabbit** [comment]
Shadows in general are much more subtle in the new stylesheet. After some discussion, we don't feel that this makes it harder to tell that it is a text entry.
