### ISSUE TITLE
Dark theme

### ISSUE THREAD

**Issue by Aliuddin27** [elementary/stylesheet#789]
in tweeks after applying prefer dark variant the the dark theme is not applying,  please help and resolve this with update
![image](https://user-images.githubusercontent.com/36618161/90785012-826e9d00-e31f-11ea-91bc-95830af7d264.png)

**Comment by danrabbit** [comment]
Tweaks is not supported by elementary. Please report the issue to the developers of that plugin.

Closing since this is not a problem with the elementary stylesheet
