### ISSUE TITLE
mouse scroll speed option needed

### ISSUE THREAD

**Issue by Aliuddin27** [elementary/stylesheet#790]
## Prerequisites
- [ ] I have searched open and closed issues for duplicates.

## Feature
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Existing work**

**Describe alternatives you've considered**

**Additional context**

**Comment by danrabbit** [comment]
Closing as a duplicate of https://github.com/elementary/switchboard-plug-mouse-touchpad/issues/21

For future issue reports, please fill out the issue template
