### ISSUE TITLE
This text is highlighted

### ISSUE THREAD

**Issue by joshuajaharwood** [elementary/stylesheet#805]
## Prerequisites
- [x] I have searched open and closed issues for duplicates.

## Describe the bug
Using dark mode on today's daily build (08/09/20) and highlighting text in an application results in the highlighted text's highlight being invisible in Firefox.

I'm not sure if this is a Firefox or Pantheon stylesheet bug. I'm using Firefox 80.0.1 64-bit.

N.b. Unfocusing the window renders the highlight visible.

### To Reproduce
1. Enable dark mode (I used the cocoa accent)
2. Start firefox, open any webpage
3. Drag left-click across some text to highlight it

### Expected behavior

I expected a beige/brown highlight as in other applications. The correct behaviour is observed in other applications, such as Epiphany.

## Platform Information

- [ ] I'm using the latest version from git that I've manually compiled
- [ ] I'm using the latest released stable version

**Comment by danrabbit** [comment]
It's a Firefox issue: https://bugzilla.mozilla.org/show_bug.cgi?id=1654323

**Comment by cassidyjames** [comment]
This has been fixed in Firefox 82, which is due to come out soon and will likely be out in time for the elementary OS 6.0 release.

![Screenshot from 2020-10-19 13 29 54](https://user-images.githubusercontent.com/611168/96502860-a3644900-120f-11eb-9ed7-e538818e0387.png)
