### ISSUE TITLE
Infobar buttons are ugly in dark style

### ISSUE THREAD

**Issue by danrabbit** [elementary/stylesheet#809]
![Screenshot from 2020-09-08 18 35 48@2x](https://user-images.githubusercontent.com/7277719/92544192-2b633600-f202-11ea-924c-3ea94efb5366.png)

**Comment by hanaral** [comment]
I think that it could either be a slightly dimmed version of the light style

**Comment by alvvaro** [comment]
Why not make the buttons transparent like in the old stylesheet?

![dark_infobar_banana300](https://user-images.githubusercontent.com/50526113/112981114-02cd6a00-915b-11eb-84f1-124d422abde8.png)

I would personally like it better if bars dimmed a bit in dark mode (esp the yellow one)

![dark_infobar_banana500](https://user-images.githubusercontent.com/50526113/112981230-2c869100-915b-11eb-83a9-912cefd863c5.png)

It can be something along the lines of:

```
&.warning revealer > box {
        
        // [...]
        
        & button {
            background-color: transparent;
            border-color: #963000;
            color: #963000;
        }
        
        @if $color-scheme == "dark" {
            background-color: $BANANA_500;
            border-color: $BANANA_900;
        }
    }
```

**Comment by hanaral** [comment]
> I would personally like it better if bars dimmed a bit in dark mode (esp the yellow one)

I feel inclined to agree, the bar is quite bright in dark style - but I feel that it makes it far more obvious that it's urgent
