### ISSUE TITLE
Sidebar outline invisible on any custom text scaling settings

### ISSUE THREAD

**Issue by hanaral** [elementary/stylesheet#825]
Default:
![Screenshot from 2020-09-14 19-54-57](https://user-images.githubusercontent.com/58219504/93126703-9c07c800-f6c4-11ea-98ac-db532e3c66f2.png)

1.06 DPI:
![Screenshot from 2020-09-14 19-55-19](https://user-images.githubusercontent.com/58219504/93126733-a88c2080-f6c4-11ea-9e24-5c515ae97403.png)

**Comment by danrabbit** [comment]
I can confirm this for anything larger than default

**Comment by jeremypw** [comment]
Playing with `granite-demo` shows that this only happens with certain widgets to the right of the sidebar - not sure what the difference is yet.
