### ISSUE TITLE
Transparent/broken labels in AppCenter headings

### ISSUE THREAD

**Issue by cassidyjames** [elementary/stylesheet#827]
So this was part of #636 I think, but I'm seeing it again since I think we reverted the specific label styling. Headings in AppCenter app listings appear transparent until the window changes focus.

**Comment by cassidyjames** [comment]
![Screenshot from 2020-09-15 12-45-59](https://user-images.githubusercontent.com/611168/93251442-6b21a480-f751-11ea-82af-e524c3037c7a.png)

**Comment by danrabbit** [comment]
Unsure if related but there are also issues with the labels in epiphany's auto complete drop down

**Comment by danrabbit** [comment]
I can't reproduce this anymore. I think we fixed it
