### ISSUE TITLE
Hdy Windows are rounded when tiled 

### ISSUE THREAD

**Issue by fabiozaramella** [elementary/stylesheet#860]
## Prerequisites
- [x] I have searched open and closed issues for duplicates.

## Describe the bug
I'm not sure if this a bug in stylesheet or in Gala but Hdy Windows remain rounded when tiled.

### To Reproduce
1. Open a normal Gtk.Window and tile it to the left
2. Now open a Hdy.Window (Music, Files, Code whatever) and tile it to the right
3. Look at how the second remain rounded
4. Cry about your OCD 😜️

### Expected behavior
Hdy Windows should become square when tiled, filling the space.

### Screenshots or screen recordings
![Schermata del 2020-10-17 20 32 18](https://user-images.githubusercontent.com/5459945/96353091-78b3ac80-10b8-11eb-9b23-283b3defeeb4.png)

- [x] I'm using the latest version from git that I've manually compiled
- [ ] I'm using the latest released stable version

## Additional context

On a fully updated Odin daily.

**Comment by Exalm** [comment]
Not fixable on elementary side, see https://gitlab.gnome.org/GNOME/libhandy/-/issues/357

**Comment by fabiozaramella** [comment]
@Exalm Thanks for reporting it upstream! 👍🏻

**Comment by Exalm** [comment]
We did discuss it with Dan previously, just need to find time to implement it. Patches welcome :)

**Comment by danirabbit** [comment]
Closing since Handy is done and this doesn't seem to be an issue with GTK 4 windows
