### ISSUE TITLE
Suggested action buttons don't follow app accent color

### ISSUE THREAD

**Issue by cassidyjames** [elementary/stylesheet#866]
## What Happened

I have been playing with setting the accent color within apps for elementary OS 6. However, suggested action buttons seem to always follow the system accent color instead of the in-app defined accent color. Do apps need to define all the shades as well?

## Expected Behavior

Setting `@define-color accent_color #f00` would set the color for suggested action buttons.

## Steps to Reproduce

1. Set the `@accent_color` for an app in its CSS
2. Use a suggested action button
3. See that it still follows the system accent color

## Platform Information

elementary OS 6 daily with stylesheet from git master

**Comment by danrabbit** [comment]
Yeah at the moment this is based on all shades which is obviously not desirable. Needs to be re-written to use just `accent_color`
