### ISSUE TITLE
Badges shouldn't be important by default

### ISSUE THREAD

**Issue by tintou** [elementary/stylesheet#876]
In Mail we use to have informative badges that were looking like this:
![Capture d'écran du 2020-11-04 15 36 01@2x](https://user-images.githubusercontent.com/745535/98125688-07943780-1eb5-11eb-9098-a765a1f99b8c.png)

We now have badges that look like important badges:
![Capture d'écran du 2020-11-04 15 36 35@2x](https://user-images.githubusercontent.com/745535/98125702-0c58eb80-1eb5-11eb-8021-13e84d3a306a.png)

In this context, the badge informs on the number of mails in a thread, not the unread mails so it's not an important information.

**Comment by danrabbit** [comment]
I'm not sure if I already implemented it, but Mail should add "flat" class here

**Comment by danrabbit** [comment]
Fixed in #925
