### ISSUE TITLE
GtkWindow not getting same styling as HandyWindow

### ISSUE THREAD

**Issue by hezral** [elementary/stylesheet#895]
## What Happened
A window using Gtk.Window does not have the outline compared to a Window with Handy.Window

## Expected Behavior
Both window should have same styling

1x scale
![1x](https://user-images.githubusercontent.com/762735/101113549-94e4bc00-361a-11eb-8247-7c4a42723243.png)
2x scale
![2x](https://user-images.githubusercontent.com/762735/101113556-97471600-361a-11eb-8cc5-b6c78f712f05.png)

## Steps to Reproduce
I'm testing this using Python but i believe it shouldn't matter since this is stylesheet related. 

**Gtk.Window code**
```
import gi
gi.require_version('Gtk', '3.0')
from gi.repository import Gtk

header = Gtk.HeaderBar()
header.props.show_close_button = True
header.props.title = "GtkWindow"

label = Gtk.Label("TEST")
label.props.expand = True
label.props.valign = label.props.halign = Gtk.Align.CENTER

grid = Gtk.Grid()
grid.props.expand = True
grid.attach(label, 0, 1, 1, 1)

win = Gtk.Window()
win.set_size_request(300,250)
win.get_style_context().add_class("rounded")
win.set_titlebar(header)
win.add(grid)

win.show_all()
win.connect("destroy", Gtk.main_quit)

Gtk.main()
```
**Handy.Window code**
```
import gi
gi.require_version('Handy', '1')
gi.require_version('Gtk', '3.0')
from gi.repository import Gtk, Handy

header = Handy.HeaderBar()
header.props.show_close_button = True
header.props.hexpand = True
header.props.title = "HandyWindow"

label = Gtk.Label("TEST")
label.props.expand = True
label.props.valign = label.props.halign = Gtk.Align.CENTER

grid = Gtk.Grid()
grid.props.expand = True
grid.attach(header, 0, 0, 1, 1)
grid.attach(label, 0, 1, 1, 1)

win = Handy.Window()
win.set_size_request(300,250)
win.add(grid)
win.show_all()
win.connect("destroy", Gtk.main_quit)

Handy.init()
Gtk.main()
```
## Platform Information
![about](https://user-images.githubusercontent.com/762735/101113570-a037e780-361a-11eb-8511-25cfd48c1521.png)

**Comment by hanaral** [comment]
From what I can tell in the images the window itself is only marginally different, but the gtk.headerbar’s outline is light grey instead of dark like hdy.headerbar

**Comment by hezral** [comment]
Yes, only the header area seems to loose that outline. I have an eye for details :)

**Comment by hezral** [comment]
Saw on the linked issue, the fix was to move to Hdy.ApplicationWindow and Hdy.Headerbar. Not actually a fix i suppose since basically its migrating to libhandy. My question would be, does that mean Gtk.Window and Gtk.Headerbar will be left out?
