### ISSUE TITLE
Renaming items in sidebars shows transparent entry on top of existing item

### ISSUE THREAD

**Issue by cassidyjames** [elementary/stylesheet#896]
I'm not sure if this is a stylesheet issue, but I think so: if I try to rename an item in a sidebar (i.e. in Files or Code), I get a transparent (and thus unreadable) entry on top of the existing item in the sidebar.

**Comment by jeremypw** [comment]
This does not seem to affect the Files sidebar-listbox PR (https://github.com/elementary/files/pull/1453) but in Code I get a transparent background entry superimposed on the row, slightly offset so that the text is unreadable.

**Comment by danrabbit** [comment]
Yeah this seems specific to tree view
