### ISSUE TITLE
Flash with focus outline in dark style

### ISSUE THREAD

**Issue by cassidyjames** [elementary/stylesheet#903]
When a button is focused in the dark style, it looks like it flashes light briefly before showing the accent color outline.

**Comment by okitoxo** [comment]
This was proofed on Odin? I can't replicate on Hera, building the stylesheet and using Gtk Inspector.

**Comment by okitoxo** [comment]
The problem
This widget have a trasition for all properties and it doesn't have a initial value of outline.

We have two ways:

- Mantain transition for all properties (other widgets don't have that behaivor in focus outlined) and set initial values for outline property.
- Restrict transition for only backgroud property (for active state)

I think second way is right to keep uniform widgets.
