### ISSUE TITLE
Audio volume and screen brightness overlays aren't flat

### ISSUE THREAD

**Issue by hanaral** [elementary/stylesheet#905]
## Expected Behavior
The overlay popups use the flat style of bars instead of the default stylised ones.

## Steps to Reproduce

1. Install lastest git stylesheet
2. Invoke any kind of overlay popup

## Images

![2020-12-16 09 54 42 のスクリーンショット](https://user-images.githubusercontent.com/58219504/102382985-edc13680-3fc2-11eb-8ab0-c8f8ff3bd685.png)
![Screenshot from 2020-12-16 09-53-30](https://user-images.githubusercontent.com/58219504/102383003-f285ea80-3fc2-11eb-862f-9988b0f5c8b6.png)

**Comment by cassidyjames** [comment]
I believe this was because you also needed the latest notifications branch; we switched from carrying the styling for the notifications specifically and instead are using a `.flat` class. Make sure you're up to date on everything. :)

**Comment by hanaral** [comment]
oops
