### ISSUE TITLE
Focused flat buttons get highlighted

### ISSUE THREAD

**Issue by tintou** [elementary/stylesheet#907]
## What Happened
There is an highligh when a flat buttons get focused
Here is in the notebook:
![Capture d'écran du 2020-12-18 09 51 51@2x](https://user-images.githubusercontent.com/745535/102594830-05113880-4117-11eb-8960-1755f86820a6.png)

## Expected Behavior
No outline when I click on the button

**Comment by cassidyjames** [comment]
Flat buttons should still have a distinct focus style for accessibility, though. I'm not sure what that should look like.
