### ISSUE TITLE
Higher contrast spinners

### ISSUE THREAD

**Issue by hanaral** [elementary/stylesheet#911]
## What Happened
Right now they look quite faded with the dark style, which makes them harder than it should be to see.

## Expected Behavior
They are a little more tinted than the current one

## Platform Information
elementary OS 6 Daily

**Comment by danrabbit** [comment]
@hanaral can you post a screenshot of the issue or describe an app where the issue can be reproduced?

This is from gtk3-widget-factory and it seems okay to me:
![Screenshot from 2020-12-29 13 59 00@2x](https://user-images.githubusercontent.com/7277719/103316683-13483a00-49de-11eb-8827-69f88f187404.png)

**Comment by hanaral** [comment]
@danrabbit I think the issue is at smaller sizes, since it looks a little mushy at 1366 by 768. It may just be the terrible colour reproduction of my ThinkPad's screen.
https://user-images.githubusercontent.com/58219504/103320646-166b1680-4a2e-11eb-95ba-7cfb8f6a182e.mp4

**Comment by cassidyjames** [comment]
@hanaral ah yeah the color on top of that highlighted row is pretty low contrast. I don't know if we can increase it there or not.
