### ISSUE TITLE
Extra margin inside dialog action areas

### ISSUE THREAD

**Issue by danrabbit** [elementary/stylesheet#914]
## What Happened

![Screenshot from 2020-12-29 14 37 39@2x](https://user-images.githubusercontent.com/7277719/103318510-7d171280-49e3-11eb-8b5d-ac6c5da5621c.png)

because of extra margin added to `.dialog-action-area` in all dialogs, not just in MessageDialogs

## Expected Behavior

![Screenshot from 2020-12-29 14 39 38@2x](https://user-images.githubusercontent.com/7277719/103318572-b485bf00-49e3-11eb-8421-8c0a96670e47.png)

**Comment by 4jNsY6fCVqZv** [comment]
I wonder why the Open button in both screenshots seems to be larger than the Cancel button!?

**Comment by danrabbit** [comment]
Fixed in https://github.com/elementary/stylesheet/pull/934
