### ISSUE TITLE
Some About dialogs translucent

### ISSUE THREAD

**Issue by cassidyjames** [elementary/stylesheet#92]
Have to confirm this, but filing it here before I forget. both Eddy (https://github.com/donadigo/eddy/issues/8) and Vocal (https://github.com/needle-and-thread/vocal/issues/157) have translucent About dialogs, and they both use the theme color. I suspect it's an issue in the stylesheet.

**Comment by cassidyjames** [comment]
Example from Vocal: ![vocal-about](https://cloud.githubusercontent.com/assets/611168/25308201/db85802e-276c-11e7-872e-01c7fc960509.png)

**Comment by cassidyjames** [comment]
Hm, might not be related to theme color; Tomato has the same issue and as far as I can tell doesn't use the theme color.
![tomato-about](https://cloud.githubusercontent.com/assets/611168/25308228/3c53558e-276d-11e7-8b33-e9a5af881e09.png)

**Comment by cassidyjames** [comment]
As far as I can tell, this is only on apps from AppCenter. Preinstalled apps like Music, Files, Mail, Videos, Terminal, and Switchboard all have normal-looking About dialogs.

**Comment by danrabbit** [comment]
Closing because this turned out to be an issue with using an old granite in Houston
