### ISSUE TITLE
Resolution issues

### ISSUE THREAD

**Issue by DaHero2031** [elementary/stylesheet#920]
Hi! i'm sorry to say that i've been experiencing issues in the default elementary apps where the apps don't fit in the screen and i have to manually move the entire window because my screen is 1024x600, i don't know if you guys want to support low resolution displays or not, but i'll leave this out here: Most of the students in Argentina get an intel classmate netbook with a 1024x600 display.
I'm really loving elementary and would like to recommend it to a lot of people, although the way that the settings menu is cut by the screen lacking 128 pixels is a bit of a drawback.
Fix it or not, i'll keep recomending this grat looking and performing distro

**Comment by danrabbit** [comment]
Hey thanks for your comment! Unfortunately the minimum display size we support is 1024x768 as outlined here: https://elementary.io/docs/installation#recommended-system-specifications

Since 1024x600 is below that size I'm going to close this as "Design Conflict"
