### ISSUE TITLE
Progressbar effect too low contrast with certain colours

### ISSUE THREAD

**Issue by hanaral** [elementary/stylesheet#942]
## What Happened

With both the light and dark style, in most accent colours the pulse in the progressbar is way too low contrast for me to see without staring at it. This is especially the case with the Banana accent colour:
![Screenshot from 2021-01-27 22-16-19](https://user-images.githubusercontent.com/58219504/106062844-4241f080-60ef-11eb-9d32-4165517019da.png)
Try to spot the pulse:
![Screenshot from 2021-01-27 22-27-07](https://user-images.githubusercontent.com/58219504/106062851-440bb400-60ef-11eb-9a45-47375d4d4f77.png)

## Expected Behavior

Maybe lean more towards a more 'condensed' and contrasty pulse effect (or even consider adding soft stripes as per my suggestion :^) )

## Steps to Reproduce

1. Open gtk3-widget-factory
2. Try spotting the existance of a pulse effect without staring

## Platform Information

elementary OS 6 Daily

**Comment by cassidyjames** [comment]
Honestly I think this is fine; if anything it means we should tweak the accent colors more broadly to be more consistent in value, but this isn't really a critical part of the UI—it's just a tiny flourish. :shrug:

It's also gonna SUPER depend on your display's color reproduction and brightness; on my displays, they're all visible but just slightly less so on the brighter accents (like yellow). I don't think we want to pursue stripes as that's a pretty strong stylistic choice and doesn't really feel right to me.

**Comment by hanaral** [comment]
> Honestly I think this is fine; if anything it means we should tweak the accent colors more broadly to be more consistent in value, but this isn't really a critical part of the UI—it's just a tiny flourish. It's also gonna SUPER depend on your display's color reproduction and brightness; on my displays, they're all visible but just slightly less so on the brighter accents (like yellow).

That sounds fine too, but I do struggle to see the pulse on all my displays. It's a little better on my iPhone's but it's still quite difficult to make out. It could just benefit from being a little more condensed by shrinking the space it takes up - but it's still entirely up to the UX team

>  I don't think we want to pursue stripes as that's a pretty strong stylistic choice and doesn't really feel right to me.

It's still just a suggestion, but I think that giving some soft-edged stripes a shot could go well with the more 'animated' character elementary OS has
