### ISSUE TITLE
Background color of some dialog in Audacity is always black

### ISSUE THREAD

**Issue by ryonakano** [elementary/stylesheet#957]
## What Happened

![Screenshot from 2021-02-25 21-05-51](https://user-images.githubusercontent.com/26003928/109151429-82a79380-77ad-11eb-82b5-05b2a22865e9.png)

Background color of some dialog in Audacity is always black even in the light style. This prevent users from seeing the content of the dialog at all.

## Expected Behavior

![Screenshot from 2021-02-25 21-06-12](https://user-images.githubusercontent.com/26003928/109151439-86d3b100-77ad-11eb-8b64-0bd52d18c7c0.png)

Background color of some dialog in Audacity should be a normal background color―not redacted―as in the previous stylesheet.

## Steps to Reproduce

1. Install and run Audacity
2. Open some dialog by selecting "Effect"→"Distortion" for example
3. See the error

## Platform Information

- elementary OS Odin Daily with fully up-to-date
- Audacity 2.3.3

P.S. I tried to check what the css class is applied here using GTK Inspector but not sure how…

**Comment by cassidyjames** [comment]
@ryonakano where is Audacity installed from on your system? We can check to see if there is something obvious we’re not setting, but I am pretty sure Audacity is using wx widgets, not GTK, which means we don't have direct control over anything there. If you install from Flathub, Audacity should use Adwaita instead of the elementary stylesheet which will at least be what it is developed and tested against.

**Comment by ryonakano** [comment]
I installed the deb-packaged one from AppCenter. Surely these dialogs look good when I select Adwaita for theme in GTK Inspector.

**Comment by danrabbit** [comment]
It's not clear why this is happening, but it does seem to work as expected in the old stylesheet and with Adwaita

**Comment by ryonakano** [comment]
Confirmed the issue still present in the latest early access (horus).

**Comment by ryonakano** [comment]
Closing because I can no longer reproduce this issue with Audacity 3.4.2 installed from apt on OS 8 RC
