### ISSUE TITLE
Make the application's titlebar square when maximized

### ISSUE THREAD

**Issue by rafaelcn** [elementary/stylesheet#96]
Have the developers thought of making the titlebar of the application square (border-radius: 0) when maximized? It would make use of the empty space left by the round-ish border. If this has already been thought, why it wasn't implemented? Is it a good design choice?

![image](https://cloud.githubusercontent.com/assets/3271143/26031589/16f07b66-3850-11e7-8d0c-b879bbcce5e8.png)

**Comment by snwh** [comment]
This is a duplicate of #73

**Comment by rafaelcn** [comment]
Thanks for pointing that out, didn't make a research before submit the issue.

**Comment by snwh** [comment]
No worries
