### ISSUE TITLE
Notification icons are dimmed

### ISSUE THREAD

**Issue by cassidyjames** [elementary/stylesheet#961]
Due to #900, I guess; since notifications are not focused, they get backdrop styles.

**Comment by cassidyjames** [comment]
I think we could just target images explicitly in buttons to solve this? https://github.com/elementary/stylesheet/commit/8a9ba6180e0faf7f22c8188e5375dcba5cf5606b#diff-cc61d0361dcc2b430bcbdeee6e70cfa018877900580c786dec09bf0efa66d0a7

**Comment by danrabbit** [comment]
Yeah we might need to get more specific here. I think we probably also want images in flowboxes and lists? But at the very least we could at least make this specific to windows, since I'm noticing weirdness when dialogs and popovers happen to be in backdrop
