### ISSUE TITLE
Translucency in dimmed icons look weird in some cases

### ISSUE THREAD

**Issue by hanaral** [elementary/stylesheet#963]
## What Happened

Unfocusing an app window can look weird if they stack Gtk.Images 

## Expected Behavior

Images are made paler () rather than transparent

## Examples

![Screenshot from 2021-03-08 11-41-58](https://user-images.githubusercontent.com/58219504/110317871-a320ea80-8004-11eb-9457-22044fb6f797.png)
![Screenshot from 2021-03-08 11-51-14](https://user-images.githubusercontent.com/58219504/110317872-a3b98100-8004-11eb-95a3-11dfe4c062d3.png)

## Platform Information

elementary OS Daily

**Comment by JoseExposito** [comment]
It was already reported: https://github.com/elementary/stylesheet/issues/961
I don't have permissions to close the issue in this repo, so fell free to do it yourself.

**Comment by danrabbit** [comment]
@cassidyjames yeah I think we probably need to scale back the image dimming and just do buttons for now and then we can try to add more widgets as we test them
