### ISSUE TITLE
Dark variant: Missing "insensitive" style for buttons in headerbar

### ISSUE THREAD

**Issue by ztefn** [elementary/stylesheet#97]
[Haguichi](https://github.com/ztefn/haguichi/) uses dark variant by default. When disconnected, the "Add", "Refresh" and "Search" buttons in the headerbar are disabled/grayed-out/insensitive. In elementary's dark theme variant insensitive buttons are colored white, which makes them seem active instead (more so than the actual sensitive buttons). The normal (light) theme variant does not have this problem.

![elementary-header-bars](https://cloud.githubusercontent.com/assets/343442/26284512/626983ce-3e3d-11e7-8066-79154835f189.png)

**Comment by ztefn** [comment]
The solution can be a simple declaration like this:
```
.titlebar .image-button:insensitive GtkImage {
    color: @insensitive_color;
}
```
In fact, this is exactly what I've now included in a [local stylesheet](https://github.com/ztefn/haguichi/blob/elementary/data/stylesheets/elementary-dark.css) embedded in my app, with the following result:
![screenshot from 2017-12-30 00-48-40 cropped](https://user-images.githubusercontent.com/343442/34449799-d5b41fd8-ecfc-11e7-9c99-f69e3fc315d9.png)

**Comment by ztefn** [comment]
This issue is still present in Juno beta 1.

**Comment by cassidyjames** [comment]
@ztefn thanks for reporting this! I think it hasn't been tackled yet because elementary apps typically do not use symbolic icons in headerbars, so it's not something we see day-to-day.

**Comment by cassidyjames** [comment]
I can confirm this in other GNOME-style apps that use symbolic icons in the headerbar.
