### ISSUE TITLE
Emoji picker styling seems broken

### ISSUE THREAD

**Issue by pushqrdx** [elementary/stylesheet#980]
![Glitch](https://user-images.githubusercontent.com/25884937/112774808-1a153600-903b-11eb-9b0e-aa838eaf299d.png)

Padding beneath the input is not correct + no border to separate the upper input container from the emoji list.

Tested on latest stylesheet from git

**Comment by jwinnie** [comment]
Can't reproduce with light theme:

![image](https://user-images.githubusercontent.com/20506149/113524989-2cc1ca80-9567-11eb-8744-a9dabcfd5633.png)

**Comment by pushqrdx** [comment]
> Can't reproduce with light theme:
> 
> ![image](https://user-images.githubusercontent.com/20506149/113524989-2cc1ca80-9567-11eb-8744-a9dabcfd5633.png)

It is reproduced in your screenshot see the blur outline is cut
