### ISSUE TITLE
Searching spinner shouldn't spin

### ISSUE THREAD

**Issue by hanaral** [elementary/stylesheet#996]
## What Happened

I keep forgetting to open this; when searching the spinner doesn't use the stylesheet's animation and spins like the gnome one instead

## Expected Behavior

no 💢️ spinning 😤️ allowed 🚫️

## Steps to Reproduce

1. Enter text in to search bar
2. Watch that mf spin

## Platform Information

elementary OS 6 Early Access

**Comment by danrabbit** [comment]
@hanaral in future issue reports, please try to use more accurate language to describe an issue. It took me a little bit to figure out what exactly the problem you were describing was
